import Link from "next/link";
import { adminGoalsAction,adminJobStatusAction,adminPaymentAction,adminReportAction,adminSupportTicketAction,adminUserStatusAction } from "@/app/actions";
import { AppShell } from "@/components/app-shell";
import { Notice } from "@/components/notice";
import { StatusPill } from "@/components/status-pill";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { money } from "@/lib/config";

type Summary={users_total:number;workers:number;employers:number;active_users:number;jobs_total:number;jobs_open:number;jobs_completed:number;monthly_completed_jobs:number;jobs_completed_clean:number;applications:number;confirmed_workers:number;pending_payments:number;confirmed_payments:number;rejected_payments:number;platform_revenue:number;monthly_revenue:number;monthly_paid_posts:number;completed_job_value:number;reports_open:number;no_shows:number};
type Goals={monthly_revenue:number;monthly_completed_jobs:number;total_users:number;monthly_paid_posts:number};
type Employer={id:string;full_name:string;phone:string;municipality:string|null;status:string;created_at:string;employer_type:string;rating_average:number|null;total_jobs:number;open_jobs:number;completed_jobs:number;paid_posts:number;platform_paid:number;completed_payroll:number};
type Worker={id:string;full_name:string;phone:string;municipality:string|null;status:string;created_at:string;age:number;zone:string;categories:string[];availability:string;completed_jobs:number;no_show_count:number;rating_average:number|null;attendance_rate:number|null;active_applications:number;total_earned:number};
type Payment={id:string;reference:string;amount:number;status:string;reported_at:string;confirmed_at:string|null;rejection_reason:string|null;job_id:string;job_title:string;job_status:string;employer_name:string;employer_phone:string;municipality:string|null};
type ConsoleData={summary:Summary;goals:Goals;employers:Employer[];workers:Worker[];payments:Payment[]};
type SupportTicket={id:string;reporter_id:string;reporter_role:string;category:string;title:string;description:string;page_context:string|null;priority:string;status:string;admin_notes:string|null;created_at:string;profile:{full_name:string;phone:string}|null};

export default async function Admin({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const {profile}=await requireUser("admin"); const q=await searchParams; const tab=q.tab??"summary"; const supabase=await createClient();
  const [{data:consoleData,error:consoleError},{data:jobs},{data:reports},{data:supportTickets,error:supportError}]=await Promise.all([
    supabase.rpc("admin_console"),supabase.from("jobs").select("*").order("created_at",{ascending:false}).limit(200),supabase.from("reports").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("support_tickets").select("*,profile:profiles!support_tickets_reporter_id_fkey(full_name,phone)").order("created_at",{ascending:false}).limit(200),
  ]);
  const data=consoleData as ConsoleData|null; const s=data?.summary; const goals=data?.goals;
  return <AppShell role="admin" name={profile.full_name}>
    <section className="admin-hero"><div><span>CONTROL SUPERADMIN</span><h1>Todo Jale,<br/>en un vistazo.</h1><p>Ingresos, usuarios, publicaciones y alertas en tiempo real.</p></div><div className="admin-live"><i/> Datos protegidos</div></section>
    {q.error&&<div className="mb-4"><Notice type="error">{q.error}</Notice></div>}{q.message&&<div className="mb-4"><Notice type="success">✓ {q.message}</Notice></div>}{consoleError&&<div className="mb-4"><Notice type="error">No se pudieron cargar las estadísticas: {consoleError.message}</Notice></div>}{supportError&&tab==="system"&&<div className="mb-4"><Notice type="error">No se pudieron consultar los tickets: {supportError.message}</Notice></div>}

    {tab==="summary"&&<><div className="admin-kpis"><Kpi tone="blue" label="Ingresos de la plataforma" value={money(s?.platform_revenue??0)} note={`${s?.confirmed_payments??0} publicaciones cobradas`}/><Kpi tone="pink" label="Ingresos este mes" value={money(s?.monthly_revenue??0)} note={`${s?.pending_payments??0} pagos esperan revisión`}/><Kpi tone="cyan" label="Usuarios registrados" value={String(s?.users_total??0)} note={`${s?.workers??0} trabajadores · ${s?.employers??0} empleadores`}/><Kpi tone="navy" label="Valor generado en jales" value={money(s?.completed_job_value??0)} note="Pagos acordados en jales concluidos"/></div>{(s?.pending_payments??0)>0&&<Link href="/admin?tab=payments" className="admin-alert"><div><b>{s?.pending_payments} pago{s?.pending_payments===1?"":"s"} por revisar</b><span>Confirma la transferencia para publicar el jale o recházala indicando el motivo.</span></div><strong>REVISAR AHORA →</strong></Link>}<section className="admin-section"><div className="admin-section-head"><div><small>OPERACIÓN</small><h2>Estado de la plataforma</h2></div><Link href="/admin?tab=goals">Configurar metas →</Link></div><div className="admin-metric-grid"><Metric label="Empleadores" value={s?.employers??0}/><Metric label="Trabajadores" value={s?.workers??0}/><Metric label="Jales publicados" value={s?.jobs_total??0}/><Metric label="Jales abiertos" value={s?.jobs_open??0}/><Metric label="Jales concluidos" value={s?.jobs_completed??0}/><Metric label="Concluidos sin reportes" value={s?.jobs_completed_clean??0}/><Metric label="Personas contratadas" value={s?.confirmed_workers??0}/><Metric label="Reportes de personas" value={s?.reports_open??0}/><Metric label="Errores del sistema" value={supportTickets?.filter(t=>!['resolved','closed'].includes(t.status)).length??0}/></div></section><section className="admin-section"><div className="admin-section-head"><div><small>METAS</small><h2>Avance del mes</h2></div></div><div className="grid md:grid-cols-2 gap-4"><Goal label="Ingresos mensuales" value={s?.monthly_revenue??0} goal={goals?.monthly_revenue??0} moneyValue/><Goal label="Jales concluidos este mes" value={s?.monthly_completed_jobs??0} goal={goals?.monthly_completed_jobs??0}/><Goal label="Usuarios totales" value={s?.users_total??0} goal={goals?.total_users??0}/><Goal label="Publicaciones pagadas este mes" value={s?.monthly_paid_posts??0} goal={goals?.monthly_paid_posts??0}/></div></section></>}

    {tab==="payments"&&<><PageTitle eyebrow="DINERO" title="Pagos por publicaciones" subtitle="Cada transferencia confirmada se suma automáticamente a tus ingresos."/><div className="grid gap-4">{data?.payments.map(p=><article className={`payment-review ${p.status}`} key={p.id}><div className="payment-main"><div><span className="payment-ref">{p.reference}</span><h3>{p.job_title}</h3><p>{p.employer_name} · {p.employer_phone} · {p.municipality||"Sin municipio"}</p><small>Reportado {new Date(p.reported_at).toLocaleString("es-MX")}</small></div><div className="payment-amount"><strong>{money(p.amount)}</strong><StatusPill status={p.status}/></div></div>{p.rejection_reason&&<p className="payment-reason">Motivo: {p.rejection_reason}</p>}{p.status==="reported"&&<div className="payment-actions"><form action={adminPaymentAction}><input type="hidden" name="payment_id" value={p.id}/><input type="hidden" name="confirm" value="true"/><button className="btn btn-primary w-full">✓ AUTORIZAR Y PUBLICAR</button></form><form action={adminPaymentAction} className="reject-form"><input type="hidden" name="payment_id" value={p.id}/><input type="hidden" name="confirm" value="false"/><select className="field" name="reason" required><option value="">Motivo del rechazo</option><option>Pago no recibido</option><option>Transferencia falsa</option><option>Monto incorrecto</option><option>Referencia incorrecta</option><option>Comprobante ilegible</option></select><button className="btn reject-button">DENEGAR</button></form></div>}</article>)}{!data?.payments.length&&<Empty icon="✓" title="No hay pagos reportados" text="Las publicaciones que requieran pago aparecerán aquí."/>}</div></>}

    {tab==="employers"&&<><PageTitle eyebrow="NEGOCIOS Y PERSONAS" title="Empleadores" subtitle="Cuántos jales publica cada uno, cuánto aporta y cuánto trabajo genera."/><div className="admin-list">{data?.employers.map(e=><details className="person-card" key={e.id}><summary><div className="person-avatar company">{e.employer_type==="Negocio"?"🏢":"👤"}</div><div className="person-name"><b>{e.full_name}</b><span>{e.employer_type} · {e.municipality||"Sin municipio"}</span></div><div className="person-highlight"><b>{e.total_jobs}</b><span>jales</span></div><StatusPill status={e.status}/><i>⌄</i></summary><div className="person-detail"><div className="detail-grid"><Metric label="Publicaciones" value={e.total_jobs}/><Metric label="Abiertas" value={e.open_jobs}/><Metric label="Concluidas" value={e.completed_jobs}/><Metric label="Pagadas" value={e.paid_posts}/><Metric label="Ingresos para Jale" value={money(e.platform_paid)}/><Metric label="Valor de trabajos" value={money(e.completed_payroll)}/><Metric label="Calificación" value={e.rating_average??"—"}/><Metric label="Registrado" value={new Date(e.created_at).toLocaleDateString("es-MX")}/></div><p className="private-data">Contacto privado: <b>{e.phone}</b></p><UserControl id={e.id} status={e.status}/></div></details>)}</div></>}

    {tab==="workers"&&<><PageTitle eyebrow="COMUNIDAD" title="Personas que buscan jale" subtitle="Actividad, reputación, asistencia y dinero generado por cada trabajador."/><div className="admin-list">{data?.workers.map(w=><details className="person-card" key={w.id}><summary><div className="person-avatar worker">{w.full_name.slice(0,1).toUpperCase()}</div><div className="person-name"><b>{w.full_name}</b><span>{w.age} años · {w.zone} · {w.municipality||"Sin municipio"}</span></div><div className="person-highlight"><b>{w.completed_jobs}</b><span>terminados</span></div><StatusPill status={w.status}/><i>⌄</i></summary><div className="person-detail"><div className="detail-grid"><Metric label="Ingreso en jales" value={money(w.total_earned)}/><Metric label="Calificación" value={w.rating_average??"—"}/><Metric label="Asistencia" value={w.attendance_rate?`${w.attendance_rate}%`:"—"}/><Metric label="Postulaciones activas" value={w.active_applications}/><Metric label="No-shows" value={w.no_show_count}/><Metric label="Registrado" value={new Date(w.created_at).toLocaleDateString("es-MX")}/></div><p className="private-data"><b>Puede hacer:</b> {w.categories?.join(" · ")}<br/><b>Disponibilidad:</b> {w.availability}<br/><b>Teléfono:</b> {w.phone}</p><UserControl id={w.id} status={w.status}/></div></details>)}</div></>}

    {tab==="jobs"&&<><PageTitle eyebrow="OPERACIÓN" title="Todos los jales" subtitle="Publicaciones, pagos acordados, fechas y estado."/><div className="card desktop-table"><table><thead><tr><th>Título</th><th>Categoría</th><th>Fecha</th><th>Pago</th><th>Personas</th><th>Estado</th></tr></thead><tbody>{jobs?.map(j=><tr key={j.id}><td><b>{j.title}</b><br/><span className="text-xs muted">{j.id.slice(0,8)}</span></td><td>{j.category}</td><td>{j.job_date}</td><td>{money(j.pay_amount)}</td><td>{j.workers_needed}</td><td><form action={adminJobStatusAction} className="flex gap-2"><input type="hidden" name="job_id" value={j.id}/><select className="field !min-h-10" name="status" defaultValue={j.status}><option value="open">Abrir</option><option value="filled">Cubierto</option><option value="completed">Terminado</option><option value="cancelled">Cancelar</option></select><button className="btn btn-soft !min-h-10">Guardar</button></form></td></tr>)}</tbody></table></div></>}

    {tab==="goals"&&<><PageTitle eyebrow="CRECIMIENTO" title="Metas de la plataforma" subtitle="Define objetivos; el tablero calculará el avance automáticamente."/><form action={adminGoalsAction} className="card admin-goals"><label className="label">Ingresos mensuales de Jale<input className="field" type="number" min="0" step="50" name="monthly_revenue" defaultValue={goals?.monthly_revenue??5000}/></label><label className="label">Jales concluidos al mes<input className="field" type="number" min="0" name="monthly_completed_jobs" defaultValue={goals?.monthly_completed_jobs??50}/></label><label className="label">Usuarios registrados totales<input className="field" type="number" min="0" name="total_users" defaultValue={goals?.total_users??100}/></label><label className="label">Publicaciones pagadas al mes<input className="field" type="number" min="0" name="monthly_paid_posts" defaultValue={goals?.monthly_paid_posts??25}/></label><button className="btn btn-primary md:col-span-2">GUARDAR METAS</button></form></>}

    {tab==="reports"&&<><PageTitle eyebrow="CONFIANZA Y SEGURIDAD" title="Reportes entre personas y no-shows" subtitle="Aquí aparecen falta de pago, impuntualidad, ausencias y mal comportamiento. Los errores técnicos están en otra sección."/><div className="report-separation"><span>👤 Reportes contra empleadores o trabajadores</span><Link href="/admin?tab=system">Ver errores del sistema →</Link></div><div className="grid gap-4">{reports?.map(r=><article className="card p-5" key={r.id}><div className="flex justify-between gap-3"><div><h3 className="font-black">{r.reason}</h3><p className="text-xs muted mt-1">Jale {r.job_id?.slice(0,8)} · {new Date(r.created_at).toLocaleDateString("es-MX")}</p></div><StatusPill status={r.status}/></div>{r.details&&<p className="mt-3">{r.details}</p>}<form action={adminReportAction} className="grid md:grid-cols-[1fr_1fr_auto] gap-2 mt-4"><input type="hidden" name="report_id" value={r.id}/><select className="field" name="status" defaultValue={r.status}><option value="reviewing">Revisando</option><option value="resolved">Resuelto</option><option value="dismissed">Descartado</option></select><input className="field" name="notes" placeholder="Notas internas"/>{r.reason==="No-show"&&<label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="remove_no_show" value="true"/> Quitar no-show</label>}<button className="btn btn-primary md:col-span-3">GUARDAR REVISIÓN</button></form></article>)}{!reports?.length&&<Empty icon="✓" title="Sin reportes pendientes" text="No hay personas reportadas por el momento."/>}</div></>}

    {tab==="system"&&<><PageTitle eyebrow="SOPORTE TÉCNICO" title="Errores del sistema" subtitle="Tickets creados por trabajadores y empleadores cuando una pantalla o función falla."/><div className="ticket-admin-summary"><Metric label="Tickets totales" value={supportTickets?.length??0}/><Metric label="Abiertos" value={supportTickets?.filter(t=>t.status==="open").length??0}/><Metric label="En revisión" value={supportTickets?.filter(t=>t.status==="in_progress").length??0}/><Metric label="Urgentes" value={supportTickets?.filter(t=>t.priority==="urgent"||t.priority==="high").length??0}/></div><div className="grid gap-4 mt-4">{(supportTickets as SupportTicket[]|null)?.map(t=><article className={`system-ticket priority-${t.priority}`} key={t.id}><div className="system-ticket-head"><div><span>#{t.id.slice(0,6).toUpperCase()} · {t.reporter_role==="worker"?"Trabajador":"Empleador"}</span><h3>{t.title}</h3><p>{t.profile?.full_name||"Usuario"} · {t.profile?.phone||"Sin teléfono"} · {new Date(t.created_at).toLocaleString("es-MX")}</p></div><div><b>{t.priority==="urgent"?"Urgente":t.priority==="high"?"Alta":t.priority==="low"?"Baja":"Normal"}</b><StatusPill status={t.status}/></div></div><p className="system-description">{t.description}</p>{t.page_context&&<p className="system-context">Ocurrió en: <b>{t.page_context}</b></p>}<form action={adminSupportTicketAction} className="ticket-admin-form"><input type="hidden" name="ticket_id" value={t.id}/><label className="label">Estado<select className="field" name="status" defaultValue={t.status}><option value="open">Recibido</option><option value="in_progress">En revisión</option><option value="waiting_user">Falta información</option><option value="resolved">Resuelto</option><option value="closed">Cerrado</option></select></label><label className="label">Prioridad<select className="field" name="priority" defaultValue={t.priority}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label className="label md:col-span-2">Respuesta para el usuario<textarea className="field min-h-24" name="admin_notes" defaultValue={t.admin_notes??""} maxLength={1200} placeholder="Qué se revisó, solución o información necesaria"/></label><button className="btn btn-primary md:col-span-2">ACTUALIZAR TICKET</button></form></article>)}{!supportTickets?.length&&<Empty icon="✓" title="Sin errores reportados" text="Los tickets técnicos de los usuarios aparecerán aquí."/>}</div></>}
  </AppShell>;
}

function Kpi({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <article className={`admin-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="admin-metric"><strong>{value}</strong><span>{label}</span></div>}
function Goal({label,value,goal,moneyValue=false}:{label:string;value:number;goal:number;moneyValue?:boolean}){const pct=goal>0?Math.min(100,Math.round(value/goal*100)):0;return <article className="goal-card"><div><b>{label}</b><span>{moneyValue?`${money(value)} de ${money(goal)}`:`${value} de ${goal}`}</span></div><strong>{pct}%</strong><div className="goal-track"><i style={{width:`${pct}%`}}/></div></article>}
function PageTitle({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div className="admin-page-title"><small>{eyebrow}</small><h1>{title}</h1><p>{subtitle}</p></div>}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="card p-9 text-center"><span className="text-4xl">{icon}</span><h3 className="font-black text-xl mt-3">{title}</h3><p className="muted mt-1">{text}</p></div>}
function UserControl({id,status}:{id:string;status:string}){return <form action={adminUserStatusAction} className="user-control"><input type="hidden" name="user_id" value={id}/><select className="field" name="status" defaultValue={status}><option value="active">Activo</option><option value="suspended">Suspendido</option><option value="blocked">Bloqueado</option></select><button className="btn btn-soft">Actualizar estado</button></form>}
