import { LegalSection,LegalShell } from "@/components/legal-shell";

export default function Privacy(){return <LegalShell eyebrow="DATOS PERSONALES" title="Aviso de privacidad integral" updated="20 de agosto de 2026">
  <LegalSection title="1. Responsable"><p><b>Responsable:</b> Mercadía [razón social o nombre legal pendiente]. <b>Domicilio:</b> [pendiente], Aguascalientes, México. <b>Contacto de privacidad:</b> [correo pendiente].</p><p>El tratamiento se rige por la <a href="https://www.diputados.gob.mx/LeyesBiblio/pdf/LFPDPPP.pdf" target="_blank" rel="noreferrer">Ley Federal de Protección de Datos Personales en Posesión de los Particulares vigente</a>.</p></LegalSection>
  <LegalSection title="2. Datos que recabamos"><ul><li>Cuenta: correo electrónico, identificador de autenticación y datos técnicos de sesión.</li><li>Perfil: nombre, teléfono, municipio, edad, colonia o zona, categorías de jales y disponibilidad.</li><li>Empleadores: tipo de solicitante, publicaciones, pagos reportados y datos de operación.</li><li>Actividad: postulaciones, confirmaciones, finalizaciones, calificaciones, reportes, no-shows y tickets de soporte.</li><li>Datos técnicos: dirección IP, navegador, dispositivo, registros de seguridad, errores y preferencias locales del tutorial.</li></ul><p>No solicitamos domicilio exacto, CV, ubicación GPS, datos bancarios del trabajador ni datos personales sensibles. No envíes información sensible en descripciones o tickets.</p></LegalSection>
  <LegalSection title="3. Finalidades primarias"><ul><li>Crear, autenticar y proteger cuentas.</li><li>Mostrar jales compatibles y administrar postulaciones, selección y confirmación.</li><li>Permitir publicación, verificación manual de cuotas y moderación.</li><li>Compartir el teléfono únicamente cuando el flujo autorizado lo requiera, por ejemplo después de una selección.</li><li>Gestionar reputación, asistencia, reportes, soporte, prevención de fraude y cumplimiento legal.</li><li>Generar métricas operativas y financieras para administrar la plataforma.</li></ul></LegalSection>
  <LegalSection title="4. Finalidades secundarias"><p>Podremos utilizar información disociada o agregada para mejorar diseño, rendimiento, estadísticas y planeación. No vendemos datos personales. Cuando una finalidad secundaria requiera consentimiento, ofreceremos un mecanismo para negarse sin afectar las funciones principales.</p></LegalSection>
  <LegalSection title="5. Encargados, transferencias y alojamiento"><p>Los datos podrán ser tratados por proveedores tecnológicos que actúan como encargados, como Supabase para autenticación y base de datos, y Vercel o Railway para alojamiento y operación. Algunos proveedores pueden procesar información fuera de México bajo medidas contractuales y de seguridad.</p><p>Podremos comunicar datos a la contraparte cuando sea necesario para ejecutar un jale confirmado, a autoridades cuando exista obligación legal, o para reconocer, ejercer o defender derechos. No se realizarán transferencias comerciales ajenas a estas finalidades sin consentimiento cuando sea exigible.</p></LegalSection>
  <LegalSection title="6. Conservación"><p>Conservaremos los datos mientras la cuenta esté activa y durante los plazos necesarios para soporte, seguridad, prevención de fraude, obligaciones legales, fiscales, contractuales y defensa de reclamaciones. Después se bloquearán o eliminarán de forma segura conforme a la normativa aplicable.</p></LegalSection>
  <LegalSection title="7. Seguridad"><p>Aplicamos controles razonables como autenticación, permisos por rol, seguridad a nivel de fila, cifrado en tránsito, registros de auditoría y acceso administrativo limitado. Ningún sistema es absolutamente invulnerable; responderemos a incidentes conforme a la ley y notificaremos cuando exista una afectación significativa.</p></LegalSection>
  <LegalSection title="8. Derechos ARCO y revocación"><p>Puedes solicitar acceso, rectificación, cancelación u oposición, así como revocar consentimiento o limitar usos, mediante el correo de privacidad pendiente de publicación. La solicitud deberá identificar al titular, describir el derecho y proporcionar información suficiente para localizar los datos. Atenderemos los plazos y requisitos de la legislación vigente.</p></LegalSection>
  <LegalSection title="9. Cookies y almacenamiento local"><p>Utilizamos cookies necesarias para mantener la sesión y almacenamiento local para preferencias como omitir o minimizar el tutorial. No se implementan rastreadores publicitarios en esta versión.</p></LegalSection>
  <LegalSection title="10. Menores"><p>Jale es exclusivamente para mayores de 18 años. Si detectamos datos de una persona menor, la cuenta podrá bloquearse y la información eliminarse conforme a la ley.</p></LegalSection>
  <LegalSection title="11. Cambios"><p>Los cambios se publicarán en esta página indicando la fecha de actualización. Cuando sean materiales, se comunicarán dentro de la plataforma y se solicitará nuevo consentimiento si la ley lo exige.</p></LegalSection>
</LegalShell>}
