import { adminBillingSettingsAction,adminDeletePackageAction,adminEmployerBillingAction,adminSavePackageAction } from "@/app/actions";
import { AppShell } from "@/components/app-shell";
import { Notice } from "@/components/notice";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { money } from "@/lib/config";

type EmployerBilling={id:string;name:string;type:string;created_at:string;free_posts_used:number;billing_exempt:boolean;free_post_credits:number;early_access:boolean;exemption_reason:string|null};
type Package={posts:number;price:number;label:string};
type BillingData={config:{charging_enabled:boolean;founding_employer_limit:number};free_posts:number;post_price_mxn:number;packages:Package[];employers:EmployerBilling[]};

export default async function Billing({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const {profile}=await requireUser("admin"); const q=await searchParams; const supabase=await createClient();
  const {data,error}=await supabase.rpc("admin_billing_console"); const billing=data as BillingData|null;
  return <AppShell role="admin" name={profile.full_name}><div className="admin-page-title"><small>MONETIZACIÓN</small><h1>Reglas de cobro</h1><p>Decide cuándo cobrar, cuántas publicaciones regalar y qué empleadores reciben beneficios especiales.</p></div>
    {q.error&&<div className="mb-4"><Notice type="error">{q.error}</Notice></div>}{q.message&&<div className="mb-4"><Notice type="success">{q.message}</Notice></div>}{error&&<Notice type="error">Ejecuta la migración 008 para activar estos controles: {error.message}</Notice>}
    {billing&&<><section className={`billing-master ${billing.config.charging_enabled?"on":"off"}`}><div><span>COBRO GLOBAL</span><h2>{billing.config.charging_enabled?"Cobros activados":"Todas las publicaciones son gratis"}</h2><p>Precio actual: {money(billing.post_price_mxn)} · {billing.free_posts} publicaciones base gratis por empleador.</p></div><b>{billing.config.charging_enabled?"ACTIVO":"PAUSADO"}</b></section>
      <form action={adminBillingSettingsAction} className="card admin-goals mt-4"><label className="label">¿Cobrar publicaciones?<select className="field" name="charging_enabled" defaultValue={String(billing.config.charging_enabled)}><option value="true">Sí, aplicar reglas de cobro</option><option value="false">No, publicar gratis para todos</option></select></label><label className="label">Publicaciones gratis para todos<input className="field" type="number" min="0" max="100" name="free_posts" defaultValue={billing.free_posts}/></label><label className="label">Primeros empleadores fundadores<input className="field" type="number" min="0" max="10000" name="founding_limit" defaultValue={billing.config.founding_employer_limit}/></label><label className="blocking-check"><input type="checkbox" name="apply_founders" value="true"/><span><b>Aplicar ahora a cuentas existentes</b><small>Marca como exentos a los primeros empleadores según la cantidad indicada.</small></span></label><button className="btn btn-primary">GUARDAR REGLAS DE COBRO</button></form>
      <section className="admin-section"><div className="admin-section-head"><div><small>PLANES DE PUBLICACIÓN</small><h2>Paquetes que vendes</h2></div><span>{billing.packages.length} planes</span></div><p className="muted mb-4">Puedes cambiar nombre, publicaciones y precio, o crear nuevos paquetes. Los empleadores verán los cambios inmediatamente.</p><div className="plan-admin-grid">{billing.packages.map(plan=><article className="plan-admin-card" key={plan.posts}><form action={adminSavePackageAction} className="plan-editor"><input type="hidden" name="original_posts" value={plan.posts}/><label className="label">Nombre<input className="field" name="label" maxLength={60} defaultValue={plan.label} required/></label><label className="label">Publicaciones<input className="field" name="posts" type="number" min="1" max="1000" defaultValue={plan.posts} required/></label><label className="label">Precio total<input className="field" name="price" type="number" min="1" max="1000000" step="1" defaultValue={plan.price} required/></label><div className="plan-unit-price">{money(plan.price/plan.posts)} por publicación</div><button className="btn btn-soft">GUARDAR CAMBIOS</button></form><form action={adminDeletePackageAction}><input type="hidden" name="posts" value={plan.posts}/><button className="plan-delete">Eliminar plan</button></form></article>)}</div><form action={adminSavePackageAction} className="card plan-new"><div><small>NUEVO PLAN</small><h3>Agregar paquete</h3></div><label className="label">Nombre<input className="field" name="label" maxLength={60} placeholder="Ej. Paquete Evento" required/></label><label className="label">Publicaciones<input className="field" name="posts" type="number" min="1" max="1000" placeholder="20" required/></label><label className="label">Precio total<input className="field" name="price" type="number" min="1" max="1000000" step="1" placeholder="600" required/></label><button className="btn btn-primary">＋ AGREGAR PLAN</button></form></section>
      <section className="admin-section"><div className="admin-section-head"><div><small>BENEFICIOS INDIVIDUALES</small><h2>Empleadores</h2></div><span>{billing.employers.length} cuentas</span></div><div className="admin-list">{billing.employers.map(e=><article className="person-card billing-person" key={e.id}><div><div className="person-avatar company">{e.type==="Negocio"?"🏢":"👤"}</div><div className="person-name"><b>{e.name}</b><span>{e.type} · {e.early_access?"Fundador · ":""}{e.free_posts_used} publicaciones base usadas</span></div><span className={e.billing_exempt?"billing-badge free":"billing-badge"}>{e.billing_exempt?"No paga":"Regla normal"}</span></div><form action={adminEmployerBillingAction} className="billing-control"><input type="hidden" name="employer_id" value={e.id}/><label className="label">Cobro individual<select className="field" name="billing_exempt" defaultValue={String(e.billing_exempt)}><option value="false">Aplicar cobro normal</option><option value="true">Publicaciones gratis sin límite</option></select></label><label className="label">Créditos gratis adicionales<input className="field" type="number" min="0" max="10000" name="free_post_credits" defaultValue={e.free_post_credits}/></label><label className="label md:col-span-2">Motivo<input className="field" name="reason" maxLength={160} defaultValue={e.exemption_reason??""} placeholder="Influencer, convenio, promoción..."/></label><button className="btn btn-soft md:col-span-2">ACTUALIZAR BENEFICIO</button></form></article>)}</div></section></>}
  </AppShell>;
}
