import { LegalSection,LegalShell } from "@/components/legal-shell";

export default function Terms(){return <LegalShell eyebrow="DOCUMENTO CONTRACTUAL" title="Términos y condiciones de uso" updated="20 de agosto de 2026">
  <LegalSection title="1. Identidad y aceptación"><p>Jale es una plataforma digital desarrollada por Mercadía en Aguascalientes, México. Al crear una cuenta, publicar un jale, postularse o utilizar la plataforma, la persona usuaria declara ser mayor de 18 años, tener capacidad legal y aceptar estos Términos, el Aviso de Privacidad y las reglas de seguridad.</p></LegalSection>
  <LegalSection title="2. Naturaleza de la plataforma"><p>Jale proporciona infraestructura tecnológica para que personas que buscan ingresos por actividades eventuales puedan encontrar a personas o negocios que requieren apoyo temporal. Jale actúa como medio de contacto e intermediación tecnológica. Salvo que se indique expresamente por escrito, Jale y Mercadía no son patrón, empleador, agencia de colocación, representante, socio, mandatario, aseguradora, fiduciario ni parte del acuerdo celebrado entre usuarios.</p><p>La publicación, postulación, selección y confirmación no garantizan la celebración, ejecución o resultado del jale. La naturaleza jurídica real de cada relación dependerá de los hechos, del nivel de subordinación y de la legislación aplicable; ninguna cláusula pretende desconocer derechos laborales irrenunciables.</p></LegalSection>
  <LegalSection title="3. Obligaciones del empleador o solicitante"><ul><li>Publicar información verdadera sobre actividad, ubicación aproximada, horario, duración, riesgos, número de personas y pago.</li><li>Pagar completa y oportunamente la cantidad anunciada y cumplir las condiciones acordadas.</li><li>Proporcionar condiciones razonables de seguridad, herramientas y equipo de protección cuando corresponda.</li><li>No discriminar, acosar, amenazar, retener documentos, imponer tareas ilícitas ni cambiar sustancialmente las condiciones sin aceptación.</li><li>Cumplir las obligaciones fiscales, civiles, laborales, de seguridad social o administrativas que resulten aplicables al caso concreto.</li></ul></LegalSection>
  <LegalSection title="4. Obligaciones de quien busca jale"><ul><li>Proporcionar información verdadera, asistir puntualmente y realizar únicamente actividades que pueda ejecutar de forma segura.</li><li>Revisar pago, horario, lugar, alcance y condiciones antes de confirmar.</li><li>No compartir cuentas, documentos falsos ni utilizar la plataforma para fraude, robo, violencia o actividades ilegales.</li><li>Informar de inmediato si existe riesgo, cambio abusivo, falta de pago o conducta inapropiada.</li></ul></LegalSection>
  <LegalSection title="5. Pago del jale"><p>El pago visible en la publicación es un acuerdo entre el solicitante y la persona trabajadora. En esta versión Jale no procesa, custodia, garantiza ni asegura el pago del jale y no funciona como cuenta de depósito o garantía. Cada usuario debe conservar evidencia del acuerdo, asistencia, entrega y pago.</p><p>Jale podrá recibir reportes, mostrar reputación, limitar cuentas y colaborar con autoridades, pero no garantiza recuperar dinero ni indemnizar pérdidas causadas por otro usuario.</p></LegalSection>
  <LegalSection title="6. Cuota por publicación"><p>Después de las publicaciones gratuitas aplicables, el solicitante podrá pagar la cuota indicada para habilitar una publicación. Esa cuota remunera el acceso y operación del servicio digital: alojamiento e infraestructura, base de datos, seguridad, soporte, moderación, mantenimiento, desarrollo, monitoreo y costos administrativos.</p><p>La cuota no forma parte del pago del trabajador, no es comisión sobre su ingreso, no constituye seguro ni garantiza candidatos o contratación. Una transferencia reportada sólo habilita la publicación cuando el administrador la confirma. Los comprobantes falsos, alterados, duplicados o no recibidos podrán rechazarse y provocar suspensión. Una vez aprobada y publicada, la cuota se considera devengada, sin perjuicio de devoluciones exigidas por la legislación de protección al consumidor o por error atribuible a Jale.</p></LegalSection>
  <LegalSection title="7. Riesgos, fraudes e incumplimientos"><p>Cada persona es responsable de evaluar a su contraparte y adoptar precauciones. Jale no garantiza identidad, solvencia, puntualidad, habilidad, conducta, seguridad del sitio, calidad, legalidad ni pago. En la máxima medida permitida por la ley, Jale no responde por estafas, impago, ausencias, retrasos, lesiones, daños, pérdidas o controversias causadas por actos u omisiones de usuarios o terceros.</p><p>Esta limitación no excluye responsabilidades que legalmente no puedan limitarse ni daños directamente atribuibles a dolo, culpa grave, incumplimiento legal o fallas de seguridad imputables a Jale.</p></LegalSection>
  <LegalSection title="8. Moderación y reportes"><p>Jale puede revisar publicaciones, solicitar información, pausar o cancelar contenido, rechazar pagos reportados, suspender cuentas y conservar evidencia cuando detecte riesgos o infracciones. Los reportes y calificaciones deben ser honestos. Reportes falsos, amenazas o campañas de hostigamiento pueden causar bloqueo.</p></LegalSection>
  <LegalSection title="9. Disponibilidad y cambios"><p>El servicio puede experimentar mantenimiento, interrupciones, errores o cambios. Jale procurará continuidad razonable, pero no garantiza disponibilidad ininterrumpida. Las funciones, precios y Términos podrán actualizarse; los cambios materiales se comunicarán antes de entrar en vigor cuando corresponda.</p></LegalSection>
  <LegalSection title="10. Propiedad intelectual"><p>La marca, diseño, software, bases de datos y contenido propio de Jale pertenecen a Mercadía o a sus licenciantes. Se concede únicamente una licencia personal, revocable y no transferible para utilizar el servicio conforme a estos Términos.</p></LegalSection>
  <LegalSection title="11. Ley aplicable y atención"><p>Estos Términos se interpretan conforme a las leyes mexicanas. Se buscará primero una solución mediante soporte. Se conservan los derechos irrenunciables de consumidores, trabajadores y titulares de datos, incluida la posibilidad de acudir ante PROFECO, autoridades laborales, de protección de datos o tribunales competentes. Para asuntos permitidos por la ley, serán competentes las autoridades de Aguascalientes, México.</p></LegalSection>
  <LegalSection title="12. Referencias normativas"><p>Documento preparado considerando la <a href="https://www.diputados.gob.mx/LeyesBiblio/ref/lfpc.htm" target="_blank" rel="noreferrer">Ley Federal de Protección al Consumidor</a>, la <a href="https://www.diputados.gob.mx/LeyesBiblio/pdf/LFPDPPP.pdf" target="_blank" rel="noreferrer">Ley Federal de Protección de Datos Personales en Posesión de los Particulares</a> y demás legislación mexicana aplicable. La operación deberá revisarse periódicamente frente a reformas legales.</p></LegalSection>
</LegalShell>}
