-- Catálogo normalizado de categorías y habilidades.
-- Mantiene jobs.category y workers.categories durante la transición para no
-- romper cuentas ni publicaciones existentes.

create table if not exists public.work_categories (
  id integer generated by default as identity primary key,
  name text not null unique,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  icon text,
  featured boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.work_skills (
  id bigint generated by default as identity primary key,
  category_id integer not null references public.work_categories(id) on delete cascade,
  name text not null,
  slug text not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  requires_verification boolean not null default false,
  trust_level text not null default 'standard' check (trust_level in ('standard','trusted','credentialed')),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(category_id,slug)
);

create table if not exists public.worker_skills (
  worker_id uuid not null references public.workers(profile_id) on delete cascade,
  skill_id bigint not null references public.work_skills(id) on delete cascade,
  level text not null check (level in ('helper','capable','experienced')),
  verified boolean not null default false,
  verified_at timestamptz,
  verified_by uuid references public.profiles(id) on delete set null,
  verification_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(worker_id,skill_id)
);

create table if not exists public.worker_categories (
  worker_id uuid not null references public.workers(profile_id) on delete cascade,
  category_id integer not null references public.work_categories(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(worker_id,category_id)
);

create table if not exists public.job_skills (
  job_id uuid not null references public.jobs(id) on delete cascade,
  skill_id bigint not null references public.work_skills(id) on delete cascade,
  min_level text check (min_level is null or min_level in ('helper','capable','experienced')),
  created_at timestamptz not null default now(),
  primary key(job_id,skill_id)
);

alter table public.jobs add column if not exists work_category_id integer references public.work_categories(id) on delete set null;

create index if not exists work_categories_active_sort_idx on public.work_categories(active,featured desc,sort_order,id);
create index if not exists work_skills_category_active_sort_idx on public.work_skills(category_id,active,sort_order,id);
create index if not exists worker_skills_skill_worker_idx on public.worker_skills(skill_id,worker_id);
create index if not exists worker_categories_category_worker_idx on public.worker_categories(category_id,worker_id);
create index if not exists job_skills_skill_job_idx on public.job_skills(skill_id,job_id);
create index if not exists jobs_open_feed_idx on public.jobs(job_date,start_time,id)
  where status in ('open','candidates_available');
create index if not exists jobs_open_category_feed_idx on public.jobs(work_category_id,municipality,job_date,start_time,id)
  where status in ('open','candidates_available');

alter table public.work_categories enable row level security;
alter table public.work_skills enable row level security;
alter table public.worker_skills enable row level security;
alter table public.worker_categories enable row level security;
alter table public.job_skills enable row level security;

drop policy if exists work_categories_read on public.work_categories;
create policy work_categories_read on public.work_categories for select using(active or public.is_admin());
drop policy if exists work_categories_admin_write on public.work_categories;
create policy work_categories_admin_write on public.work_categories for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists work_skills_read on public.work_skills;
create policy work_skills_read on public.work_skills for select using(active or public.is_admin());
drop policy if exists work_skills_admin_write on public.work_skills;
create policy work_skills_admin_write on public.work_skills for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists worker_skills_owner_admin_read on public.worker_skills;
create policy worker_skills_owner_admin_read on public.worker_skills for select using(worker_id=auth.uid() or public.is_admin());
drop policy if exists worker_categories_owner_admin_read on public.worker_categories;
create policy worker_categories_owner_admin_read on public.worker_categories for select using(worker_id=auth.uid() or public.is_admin());

drop policy if exists job_skills_related_read on public.job_skills;
create policy job_skills_related_read on public.job_skills for select using(
  exists(
    select 1 from public.jobs j
    where j.id=job_id and (
      j.status in ('open','candidates_available') or j.employer_id=auth.uid()
      or public.is_admin() or public.has_job_application(j.id)
    )
  )
);

create or replace function public.replace_my_worker_skills(p_items jsonb,p_category_names text[] default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles where id=auth.uid() and role='worker' and status='active') then
    raise exception 'No autorizado';
  end if;
  if jsonb_typeof(coalesce(p_items,'[]'::jsonb)) <> 'array' then raise exception 'Formato de habilidades inválido'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb)) > 80 then raise exception 'Elige máximo 80 habilidades'; end if;

  delete from worker_skills where worker_id=auth.uid();
  insert into worker_skills(worker_id,skill_id,level)
  select auth.uid(),x.skill_id,max(x.level)
  from jsonb_to_recordset(coalesce(p_items,'[]'::jsonb)) as x(skill_id bigint,level text)
  join work_skills s on s.id=x.skill_id and s.active
  where x.level in ('helper','capable','experienced')
  group by x.skill_id
  on conflict(worker_id,skill_id) do update set level=excluded.level,updated_at=now();

  delete from worker_categories where worker_id=auth.uid();
  insert into worker_categories(worker_id,category_id)
  select auth.uid(),c.id from work_categories c
  where exists(select 1 from unnest(coalesce(p_category_names,'{}'::text[])) as chosen(name) where lower(chosen.name)=lower(c.name))
  on conflict do nothing;
  insert into worker_categories(worker_id,category_id)
  select distinct auth.uid(),s.category_id
  from worker_skills ws join work_skills s on s.id=ws.skill_id
  where ws.worker_id=auth.uid()
  on conflict do nothing;
end $$;

create or replace function public.get_job_candidate_skills(p_job_id uuid)
returns table(worker_id uuid,skills jsonb)
language plpgsql security definer set search_path=public as $$
begin
  if not public.is_job_employer(p_job_id) and not public.is_admin() then raise exception 'No autorizado'; end if;
  return query
  select a.worker_id,coalesce(jsonb_agg(jsonb_build_object('name',s.name,'level',ws.level,'verified',ws.verified) order by s.name) filter(where s.id is not null),'[]'::jsonb)
  from applications a
  left join worker_skills ws on ws.worker_id=a.worker_id
  left join work_skills s on s.id=ws.skill_id and s.active
  where a.job_id=p_job_id
  group by a.worker_id;
end $$;

create or replace function public.replace_job_skills(p_job_id uuid,p_skill_ids bigint[])
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from jobs where id=p_job_id and employer_id=auth.uid()) then raise exception 'No autorizado'; end if;
  if coalesce(cardinality(p_skill_ids),0) > 20 then raise exception 'Elige máximo 20 actividades'; end if;
  delete from job_skills where job_id=p_job_id;
  insert into job_skills(job_id,skill_id)
  select p_job_id,s.id from work_skills s where s.id=any(coalesce(p_skill_ids,'{}'::bigint[])) and s.active
  on conflict do nothing;
end $$;

create or replace function public.sync_job_work_category()
returns trigger language plpgsql set search_path=public as $$
begin
  select id into new.work_category_id from work_categories where lower(name)=lower(new.category) limit 1;
  return new;
end $$;

drop trigger if exists jobs_sync_work_category on public.jobs;
create trigger jobs_sync_work_category before insert or update of category on public.jobs
for each row execute function public.sync_job_work_category();

revoke all on public.work_categories,public.work_skills,public.worker_skills,public.worker_categories,public.job_skills from anon,authenticated;
grant select on public.work_categories,public.work_skills to anon,authenticated;
grant select on public.worker_skills,public.worker_categories,public.job_skills to authenticated;
grant execute on function public.replace_my_worker_skills(jsonb,text[]),public.replace_job_skills(uuid,bigint[]),public.get_job_candidate_skills(uuid) to authenticated;
