-- Datos iniciales del catálogo Jale. Generados del catálogo funcional aprobado.
insert into public.work_categories(name,slug,featured,active,sort_order) values
  ('Ayudante general','ayudante-general',true,true,1),
  ('Carga y descarga','carga-y-descarga',true,true,2),
  ('Mudanzas','mudanzas',true,true,3),
  ('Construcción','construccion',true,true,4),
  ('Pintura','pintura',true,true,5),
  ('Electricidad','electricidad',false,true,6),
  ('Plomería','plomeria',false,true,7),
  ('Carpintería y muebles','carpinteria-y-muebles',false,true,8),
  ('Herrería y metal','herreria-y-metal',false,true,9),
  ('Limpieza','limpieza',true,true,10),
  ('Jardinería','jardineria',true,true,11),
  ('Campo y actividades agrícolas','campo-y-actividades-agricolas',true,true,12),
  ('Eventos','eventos',true,true,13),
  ('Mesero y servicio de alimentos','mesero-y-servicio-de-alimentos',true,true,14),
  ('Barra y bebidas','barra-y-bebidas',true,true,15),
  ('Cocina','cocina',true,true,16),
  ('Almacén y bodega','almacen-y-bodega',true,true,17),
  ('Inventarios','inventarios',true,true,18),
  ('Tiendas y comercio','tiendas-y-comercio',true,true,19),
  ('Promotores y activaciones','promotores-y-activaciones',false,true,20),
  ('Repartos, mandados y diligencias','repartos-mandados-y-diligencias',true,true,21),
  ('Chofer y traslado','chofer-y-traslado',false,true,22),
  ('Oficina y captura','oficina-y-captura',true,true,23),
  ('Tecnología y computación','tecnologia-y-computacion',true,true,24),
  ('Fotografía, video y contenido','fotografia-video-y-contenido',false,true,25),
  ('Redes sociales y promoción digital','redes-sociales-y-promocion-digital',false,true,26),
  ('Belleza y cuidado personal','belleza-y-cuidado-personal',false,true,27),
  ('Decoración','decoracion',false,true,28),
  ('Florería','floreria',false,true,29),
  ('Mascotas','mascotas',false,true,30),
  ('Lavado y limpieza de vehículos','lavado-y-limpieza-de-vehiculos',false,true,31),
  ('Mecánica y vehículos','mecanica-y-vehiculos',false,true,32),
  ('Instalaciones y montaje','instalaciones-y-montaje',false,true,33),
  ('Audio, iluminación y eventos técnicos','audio-iluminacion-y-eventos-tecnicos',false,true,34),
  ('Costura y textiles','costura-y-textiles',false,true,35),
  ('Empaque y producción','empaque-y-produccion',false,true,36),
  ('Ferias, mercados y tianguis','ferias-mercados-y-tianguis',false,true,37),
  ('Restaurantes y comida rápida','restaurantes-y-comida-rapida',false,true,38),
  ('Hoteles y hospedaje','hoteles-y-hospedaje',false,true,39),
  ('Lavandería','lavanderia',false,true,40),
  ('Escuelas, cursos y talleres','escuelas-cursos-y-talleres',false,true,41),
  ('Logística','logistica',false,true,42),
  ('Volanteo y publicidad física','volanteo-y-publicidad-fisica',false,true,43),
  ('Atención al cliente temporal','atencion-al-cliente-temporal',false,true,44),
  ('Cobro y caja','cobro-y-caja',false,true,45),
  ('Seguridad y control de acceso','seguridad-y-control-de-acceso',false,true,46),
  ('Limpieza de terrenos y exteriores','limpieza-de-terrenos-y-exteriores',false,true,47),
  ('Recolección y separación','recoleccion-y-separacion',false,true,48),
  ('Armado de pedidos y comercio electrónico','armado-de-pedidos-y-comercio-electronico',false,true,49),
  ('Trabajos sencillos por encargo','trabajos-sencillos-por-encargo',false,true,50),
  ('Otro','otro',true,true,51)
on conflict(slug) do update set name=excluded.name,featured=excluded.featured,active=true,sort_order=excluded.sort_order;

with catalog(category_slug,name,slug,requires_verification,trust_level,sort_order) as (values
  ('ayudante-general','Ayudar a cargar cosas','ayudar-a-cargar-cosas',false,'standard',1),
  ('ayudante-general','Ayudar a acomodar mercancía','ayudar-a-acomodar-mercancia',false,'standard',2),
  ('ayudante-general','Mover cajas','mover-cajas',false,'trusted',3),
  ('ayudante-general','Limpiar área de trabajo','limpiar-area-de-trabajo',false,'standard',4),
  ('ayudante-general','Barrer','barrer',false,'standard',5),
  ('ayudante-general','Trapear','trapear',false,'standard',6),
  ('ayudante-general','Recoger basura','recoger-basura',false,'standard',7),
  ('ayudante-general','Acomodar muebles','acomodar-muebles',false,'standard',8),
  ('ayudante-general','Armar paquetes','armar-paquetes',false,'standard',9),
  ('ayudante-general','Desarmar paquetes','desarmar-paquetes',false,'standard',10),
  ('ayudante-general','Separar productos','separar-productos',false,'standard',11),
  ('ayudante-general','Etiquetar productos','etiquetar-productos',false,'standard',12),
  ('ayudante-general','Contar productos','contar-productos',false,'standard',13),
  ('ayudante-general','Empacar','empacar',false,'standard',14),
  ('ayudante-general','Desempacar','desempacar',false,'standard',15),
  ('ayudante-general','Repartir material','repartir-material',false,'standard',16),
  ('ayudante-general','Apoyar en eventos','apoyar-en-eventos',false,'standard',17),
  ('ayudante-general','Apoyar en montajes','apoyar-en-montajes',false,'standard',18),
  ('ayudante-general','Apoyar en desmontajes','apoyar-en-desmontajes',false,'standard',19),
  ('ayudante-general','Hacer mandados','hacer-mandados',false,'standard',20),
  ('ayudante-general','Llevar objetos de un lugar a otro','llevar-objetos-de-un-lugar-a-otro',false,'standard',21),
  ('ayudante-general','Llevar documentos','llevar-documentos',false,'standard',22),
  ('ayudante-general','Recoger documentos','recoger-documentos',false,'standard',23),
  ('ayudante-general','Hacer fila o recoger pedidos','hacer-fila-o-recoger-pedidos',false,'standard',24),
  ('ayudante-general','Apoyar donde haga falta','apoyar-donde-haga-falta',false,'standard',25),
  ('carga-y-descarga','Cargar cajas','cargar-cajas',false,'trusted',1),
  ('carga-y-descarga','Descargar cajas','descargar-cajas',false,'trusted',2),
  ('carga-y-descarga','Cargar mercancía','cargar-mercancia',false,'standard',3),
  ('carga-y-descarga','Descargar mercancía','descargar-mercancia',false,'standard',4),
  ('carga-y-descarga','Cargar muebles','cargar-muebles',false,'standard',5),
  ('carga-y-descarga','Descargar muebles','descargar-muebles',false,'standard',6),
  ('carga-y-descarga','Cargar electrodomésticos','cargar-electrodomesticos',false,'standard',7),
  ('carga-y-descarga','Descargar electrodomésticos','descargar-electrodomesticos',false,'standard',8),
  ('carga-y-descarga','Mover material de construcción','mover-material-de-construccion',false,'standard',9),
  ('carga-y-descarga','Cargar costales','cargar-costales',false,'standard',10),
  ('carga-y-descarga','Descargar costales','descargar-costales',false,'standard',11),
  ('carga-y-descarga','Acomodar mercancía','acomodar-mercancia',false,'standard',12),
  ('carga-y-descarga','Estibar','estibar',false,'standard',13),
  ('carga-y-descarga','Desestibar','desestibar',false,'standard',14),
  ('carga-y-descarga','Paletizar','paletizar',false,'standard',15),
  ('carga-y-descarga','Emplayar mercancía','emplayar-mercancia',false,'standard',16),
  ('carga-y-descarga','Flejar mercancía','flejar-mercancia',false,'standard',17),
  ('carga-y-descarga','Separar mercancía','separar-mercancia',false,'standard',18),
  ('carga-y-descarga','Clasificar mercancía','clasificar-mercancia',false,'standard',19),
  ('carga-y-descarga','Carga manual pesada','carga-manual-pesada',false,'standard',20),
  ('carga-y-descarga','Carga ligera','carga-ligera',false,'standard',21),
  ('carga-y-descarga','Uso de diablito','uso-de-diablito',false,'standard',22),
  ('carga-y-descarga','Uso de patín hidráulico','uso-de-patin-hidraulico',false,'standard',23),
  ('carga-y-descarga','Uso de rampa','uso-de-rampa',false,'standard',24),
  ('carga-y-descarga','Apoyo en camiones','apoyo-en-camiones',false,'standard',25),
  ('carga-y-descarga','Apoyo en bodegas','apoyo-en-bodegas',false,'standard',26),
  ('mudanzas','Cargar muebles','cargar-muebles',false,'standard',1),
  ('mudanzas','Descargar muebles','descargar-muebles',false,'standard',2),
  ('mudanzas','Empacar pertenencias','empacar-pertenencias',false,'standard',3),
  ('mudanzas','Desempacar pertenencias','desempacar-pertenencias',false,'standard',4),
  ('mudanzas','Proteger muebles','proteger-muebles',false,'standard',5),
  ('mudanzas','Emplayar muebles','emplayar-muebles',false,'standard',6),
  ('mudanzas','Desarmar muebles','desarmar-muebles',false,'standard',7),
  ('mudanzas','Armar muebles','armar-muebles',false,'standard',8),
  ('mudanzas','Mover refrigeradores','mover-refrigeradores',false,'standard',9),
  ('mudanzas','Mover lavadoras','mover-lavadoras',false,'standard',10),
  ('mudanzas','Mover colchones','mover-colchones',false,'standard',11),
  ('mudanzas','Mover salas','mover-salas',false,'standard',12),
  ('mudanzas','Mover escritorios','mover-escritorios',false,'standard',13),
  ('mudanzas','Mover cajas','mover-cajas',false,'trusted',14),
  ('mudanzas','Acomodar muebles','acomodar-muebles',false,'standard',15),
  ('mudanzas','Subir objetos por escaleras','subir-objetos-por-escaleras',false,'standard',16),
  ('mudanzas','Bajar objetos por escaleras','bajar-objetos-por-escaleras',false,'standard',17),
  ('mudanzas','Limpieza posterior a mudanza','limpieza-posterior-a-mudanza',false,'standard',18),
  ('mudanzas','Apoyo general de mudanza','apoyo-general-de-mudanza',false,'standard',19),
  ('construccion','Peón','peon',false,'standard',1),
  ('construccion','Ayudante de albañil','ayudante-de-albanil',false,'standard',2),
  ('construccion','Albañilería','albanileria',false,'standard',3),
  ('construccion','Preparar mezcla','preparar-mezcla',false,'standard',4),
  ('construccion','Acarrear material','acarrear-material',false,'standard',5),
  ('construccion','Colar concreto','colar-concreto',false,'standard',6),
  ('construccion','Demolición manual','demolicion-manual',false,'standard',7),
  ('construccion','Levantar muro','levantar-muro',false,'standard',8),
  ('construccion','Pegar block','pegar-block',false,'standard',9),
  ('construccion','Pegar ladrillo','pegar-ladrillo',false,'standard',10),
  ('construccion','Aplanado','aplanado',false,'standard',11),
  ('construccion','Enjarre','enjarre',false,'standard',12),
  ('construccion','Resanar','resanar',false,'standard',13),
  ('construccion','Colocar piso','colocar-piso',false,'standard',14),
  ('construccion','Colocar azulejo','colocar-azulejo',false,'standard',15),
  ('construccion','Colocar loseta','colocar-loseta',false,'standard',16),
  ('construccion','Boquilla','boquilla',false,'standard',17),
  ('construccion','Impermeabilización','impermeabilizacion',false,'standard',18),
  ('construccion','Aplicación de sellador','aplicacion-de-sellador',false,'standard',19),
  ('construccion','Yeso','yeso',false,'standard',20),
  ('construccion','Plafón','plafon',false,'standard',21),
  ('construccion','Tablaroca','tablaroca',false,'standard',22),
  ('construccion','Cimbra','cimbra',false,'standard',23),
  ('construccion','Descimbrar','descimbrar',false,'standard',24),
  ('construccion','Apoyo en obra','apoyo-en-obra',false,'standard',25),
  ('construccion','Limpieza de obra','limpieza-de-obra',false,'standard',26),
  ('construccion','Retiro de escombro','retiro-de-escombro',false,'standard',27),
  ('pintura','Pintar interiores','pintar-interiores',false,'standard',1),
  ('pintura','Pintar exteriores','pintar-exteriores',false,'standard',2),
  ('pintura','Pintar paredes','pintar-paredes',false,'standard',3),
  ('pintura','Pintar techos','pintar-techos',false,'standard',4),
  ('pintura','Pintar fachadas','pintar-fachadas',false,'standard',5),
  ('pintura','Pintar bardas','pintar-bardas',false,'standard',6),
  ('pintura','Pintar puertas','pintar-puertas',false,'standard',7),
  ('pintura','Pintar herrería','pintar-herreria',false,'standard',8),
  ('pintura','Aplicar primer','aplicar-primer',false,'standard',9),
  ('pintura','Aplicar sellador','aplicar-sellador',false,'standard',10),
  ('pintura','Resanar antes de pintar','resanar-antes-de-pintar',false,'standard',11),
  ('pintura','Lijar','lijar',false,'standard',12),
  ('pintura','Enmascarar','enmascarar',false,'standard',13),
  ('pintura','Preparar superficie','preparar-superficie',false,'standard',14),
  ('pintura','Usar rodillo','usar-rodillo',false,'standard',15),
  ('pintura','Usar brocha','usar-brocha',false,'standard',16),
  ('pintura','Usar pistola para pintar','usar-pistola-para-pintar',false,'standard',17),
  ('pintura','Pintura decorativa básica','pintura-decorativa-basica',false,'standard',18),
  ('pintura','Limpieza después de pintar','limpieza-despues-de-pintar',false,'standard',19),
  ('electricidad','Ayudante de electricista','ayudante-de-electricista',true,'standard',1),
  ('electricidad','Cambiar focos','cambiar-focos',true,'standard',2),
  ('electricidad','Cambiar lámparas','cambiar-lamparas',true,'standard',3),
  ('electricidad','Instalar lámparas','instalar-lamparas',true,'standard',4),
  ('electricidad','Cambiar apagadores','cambiar-apagadores',true,'standard',5),
  ('electricidad','Cambiar contactos','cambiar-contactos',true,'standard',6),
  ('electricidad','Colocar extensiones','colocar-extensiones',true,'standard',7),
  ('electricidad','Pasar cable','pasar-cable',true,'standard',8),
  ('electricidad','Canalización','canalizacion',true,'standard',9),
  ('electricidad','Instalar tubería eléctrica','instalar-tuberia-electrica',true,'standard',10),
  ('electricidad','Cableado residencial','cableado-residencial',true,'standard',11),
  ('electricidad','Instalaciones eléctricas básicas','instalaciones-electricas-basicas',true,'standard',12),
  ('electricidad','Instalación de ventiladores','instalacion-de-ventiladores',true,'standard',13),
  ('electricidad','Instalación de reflectores','instalacion-de-reflectores',true,'standard',14),
  ('electricidad','Diagnóstico eléctrico','diagnostico-electrico',true,'standard',15),
  ('electricidad','Uso de multímetro','uso-de-multimetro',true,'standard',16),
  ('electricidad','Tableros eléctricos','tableros-electricos',true,'standard',17),
  ('electricidad','Instalaciones comerciales','instalaciones-comerciales',true,'standard',18),
  ('electricidad','Electricista con experiencia','electricista-con-experiencia',true,'standard',19),
  ('plomeria','Ayudante de plomero','ayudante-de-plomero',true,'standard',1),
  ('plomeria','Cambiar llaves','cambiar-llaves',true,'standard',2),
  ('plomeria','Cambiar mezcladoras','cambiar-mezcladoras',true,'standard',3),
  ('plomeria','Reparar fugas sencillas','reparar-fugas-sencillas',true,'standard',4),
  ('plomeria','Cambiar mangueras','cambiar-mangueras',true,'standard',5),
  ('plomeria','Cambiar flotador de WC','cambiar-flotador-de-wc',true,'standard',6),
  ('plomeria','Destapar tuberías','destapar-tuberias',true,'standard',7),
  ('plomeria','Instalar lavabo','instalar-lavabo',true,'standard',8),
  ('plomeria','Instalar fregadero','instalar-fregadero',true,'standard',9),
  ('plomeria','Instalar sanitario','instalar-sanitario',true,'standard',10),
  ('plomeria','Colocar tubería PVC','colocar-tuberia-pvc',true,'standard',11),
  ('plomeria','Colocar tubería hidráulica','colocar-tuberia-hidraulica',true,'standard',12),
  ('plomeria','Reparaciones hidráulicas','reparaciones-hidraulicas',true,'standard',13),
  ('plomeria','Instalación de tinaco','instalacion-de-tinaco',true,'standard',14),
  ('plomeria','Instalación de bomba','instalacion-de-bomba',true,'standard',15),
  ('plomeria','Plomería residencial','plomeria-residencial',true,'standard',16),
  ('plomeria','Plomero con experiencia','plomero-con-experiencia',true,'standard',17),
  ('carpinteria-y-muebles','Ayudante de carpintero','ayudante-de-carpintero',false,'standard',1),
  ('carpinteria-y-muebles','Armar muebles','armar-muebles',false,'standard',2),
  ('carpinteria-y-muebles','Desarmar muebles','desarmar-muebles',false,'standard',3),
  ('carpinteria-y-muebles','Instalar repisas','instalar-repisas',false,'standard',4),
  ('carpinteria-y-muebles','Colocar puertas','colocar-puertas',false,'standard',5),
  ('carpinteria-y-muebles','Ajustar puertas','ajustar-puertas',false,'standard',6),
  ('carpinteria-y-muebles','Lijar madera','lijar-madera',false,'standard',7),
  ('carpinteria-y-muebles','Pintar madera','pintar-madera',false,'standard',8),
  ('carpinteria-y-muebles','Barnizar','barnizar',false,'standard',9),
  ('carpinteria-y-muebles','Cortar madera','cortar-madera',false,'standard',10),
  ('carpinteria-y-muebles','Reparar muebles','reparar-muebles',false,'standard',11),
  ('carpinteria-y-muebles','Fabricación básica','fabricacion-basica',false,'standard',12),
  ('carpinteria-y-muebles','Instalación de cocinas','instalacion-de-cocinas',false,'standard',13),
  ('carpinteria-y-muebles','Instalación de clósets','instalacion-de-closets',false,'standard',14),
  ('carpinteria-y-muebles','Carpintería con experiencia','carpinteria-con-experiencia',true,'standard',15),
  ('herreria-y-metal','Ayudante de herrero','ayudante-de-herrero',true,'standard',1),
  ('herreria-y-metal','Cargar perfiles','cargar-perfiles',true,'standard',2),
  ('herreria-y-metal','Cortar metal','cortar-metal',true,'standard',3),
  ('herreria-y-metal','Lijar metal','lijar-metal',true,'standard',4),
  ('herreria-y-metal','Pintar herrería','pintar-herreria',true,'standard',5),
  ('herreria-y-metal','Uso de esmeril','uso-de-esmeril',true,'standard',6),
  ('herreria-y-metal','Soldadura','soldadura',true,'standard',7),
  ('herreria-y-metal','Soldadura con electrodo','soldadura-con-electrodo',true,'standard',8),
  ('herreria-y-metal','Soldadura MIG','soldadura-mig',true,'standard',9),
  ('herreria-y-metal','Reparación de puertas','reparacion-de-puertas',true,'standard',10),
  ('herreria-y-metal','Reparación de protecciones','reparacion-de-protecciones',true,'standard',11),
  ('herreria-y-metal','Fabricación de estructuras','fabricacion-de-estructuras',true,'standard',12),
  ('herreria-y-metal','Montaje de estructuras','montaje-de-estructuras',true,'standard',13),
  ('herreria-y-metal','Herrería con experiencia','herreria-con-experiencia',true,'standard',14),
  ('limpieza','Barrer','barrer',false,'standard',1),
  ('limpieza','Trapear','trapear',false,'standard',2),
  ('limpieza','Sacudir','sacudir',false,'standard',3),
  ('limpieza','Limpiar baños','limpiar-banos',false,'standard',4),
  ('limpieza','Limpiar cocina','limpiar-cocina',false,'standard',5),
  ('limpieza','Lavar trastes','lavar-trastes',false,'standard',6),
  ('limpieza','Limpieza de ventanas','limpieza-de-ventanas',false,'standard',7),
  ('limpieza','Limpieza profunda','limpieza-profunda',false,'standard',8),
  ('limpieza','Limpieza después de fiesta','limpieza-despues-de-fiesta',false,'standard',9),
  ('limpieza','Limpieza después de mudanza','limpieza-despues-de-mudanza',false,'standard',10),
  ('limpieza','Limpieza de oficina','limpieza-de-oficina',false,'standard',11),
  ('limpieza','Limpieza de local','limpieza-de-local',false,'standard',12),
  ('limpieza','Limpieza de restaurante','limpieza-de-restaurante',false,'standard',13),
  ('limpieza','Limpieza de bodega','limpieza-de-bodega',false,'standard',14),
  ('limpieza','Limpieza de consultorio','limpieza-de-consultorio',false,'standard',15),
  ('limpieza','Limpieza de salón','limpieza-de-salon',false,'standard',16),
  ('limpieza','Limpieza de baños','limpieza-de-banos',false,'standard',17),
  ('limpieza','Limpieza de áreas comunes','limpieza-de-areas-comunes',false,'standard',18),
  ('limpieza','Limpieza después de obra','limpieza-despues-de-obra',false,'standard',19),
  ('limpieza','Limpieza de vidrios','limpieza-de-vidrios',false,'standard',20),
  ('limpieza','Lavado de pisos','lavado-de-pisos',false,'standard',21),
  ('limpieza','Limpieza de patios','limpieza-de-patios',false,'standard',22),
  ('limpieza','Limpieza de cocheras','limpieza-de-cocheras',false,'standard',23),
  ('limpieza','Retiro de basura','retiro-de-basura',false,'standard',24),
  ('limpieza','Limpieza pesada','limpieza-pesada',false,'standard',25),
  ('jardineria','Cortar pasto','cortar-pasto',false,'standard',1),
  ('jardineria','Regar plantas','regar-plantas',false,'standard',2),
  ('jardineria','Barrer jardín','barrer-jardin',false,'standard',3),
  ('jardineria','Quitar hierba','quitar-hierba',false,'standard',4),
  ('jardineria','Deshierbar','deshierbar',false,'standard',5),
  ('jardineria','Podar arbustos','podar-arbustos',false,'standard',6),
  ('jardineria','Podar plantas','podar-plantas',false,'standard',7),
  ('jardineria','Plantar','plantar',false,'standard',8),
  ('jardineria','Trasplantar','trasplantar',false,'standard',9),
  ('jardineria','Aplicar tierra','aplicar-tierra',false,'standard',10),
  ('jardineria','Colocar composta','colocar-composta',false,'standard',11),
  ('jardineria','Limpieza de jardín','limpieza-de-jardin',false,'standard',12),
  ('jardineria','Recoger hojas','recoger-hojas',false,'standard',13),
  ('jardineria','Mantenimiento básico','mantenimiento-basico',false,'standard',14),
  ('jardineria','Uso de podadora','uso-de-podadora',false,'standard',15),
  ('jardineria','Uso de desbrozadora','uso-de-desbrozadora',false,'standard',16),
  ('jardineria','Poda de árboles pequeños','poda-de-arboles-pequenos',false,'standard',17),
  ('jardineria','Jardinería con experiencia','jardineria-con-experiencia',true,'standard',18),
  ('campo-y-actividades-agricolas','Corte de fruta','corte-de-fruta',false,'standard',1),
  ('campo-y-actividades-agricolas','Corte de verdura','corte-de-verdura',false,'standard',2),
  ('campo-y-actividades-agricolas','Cosecha','cosecha',false,'standard',3),
  ('campo-y-actividades-agricolas','Siembra','siembra',false,'standard',4),
  ('campo-y-actividades-agricolas','Plantación','plantacion',false,'standard',5),
  ('campo-y-actividades-agricolas','Deshierbe','deshierbe',false,'standard',6),
  ('campo-y-actividades-agricolas','Riego','riego',false,'standard',7),
  ('campo-y-actividades-agricolas','Limpieza de terreno','limpieza-de-terreno',false,'standard',8),
  ('campo-y-actividades-agricolas','Selección de producto','seleccion-de-producto',false,'standard',9),
  ('campo-y-actividades-agricolas','Empaque agrícola','empaque-agricola',false,'standard',10),
  ('campo-y-actividades-agricolas','Carga de cajas','carga-de-cajas',false,'trusted',11),
  ('campo-y-actividades-agricolas','Carga de costales','carga-de-costales',false,'standard',12),
  ('campo-y-actividades-agricolas','Acomodo de producto','acomodo-de-producto',false,'standard',13),
  ('campo-y-actividades-agricolas','Apoyo en invernadero','apoyo-en-invernadero',false,'standard',14),
  ('campo-y-actividades-agricolas','Limpieza de invernadero','limpieza-de-invernadero',false,'standard',15),
  ('campo-y-actividades-agricolas','Alimentación de animales','alimentacion-de-animales',false,'standard',16),
  ('campo-y-actividades-agricolas','Limpieza de corrales','limpieza-de-corrales',false,'standard',17),
  ('campo-y-actividades-agricolas','Apoyo general de campo','apoyo-general-de-campo',false,'standard',18),
  ('eventos','Montar mesas','montar-mesas',false,'standard',1),
  ('eventos','Montar sillas','montar-sillas',false,'standard',2),
  ('eventos','Acomodar mobiliario','acomodar-mobiliario',false,'standard',3),
  ('eventos','Colocar manteles','colocar-manteles',false,'standard',4),
  ('eventos','Colocar decoración','colocar-decoracion',false,'standard',5),
  ('eventos','Inflar globos','inflar-globos',false,'standard',6),
  ('eventos','Montar escenarios','montar-escenarios',false,'standard',7),
  ('eventos','Montar stands','montar-stands',false,'standard',8),
  ('eventos','Colocar lonas','colocar-lonas',false,'standard',9),
  ('eventos','Montar carpas','montar-carpas',false,'standard',10),
  ('eventos','Montar equipo','montar-equipo',false,'standard',11),
  ('eventos','Descargar material','descargar-material',false,'standard',12),
  ('eventos','Recibir invitados','recibir-invitados',false,'standard',13),
  ('eventos','Control de acceso','control-de-acceso',false,'standard',14),
  ('eventos','Entregar pulseras','entregar-pulseras',false,'standard',15),
  ('eventos','Entregar boletos','entregar-boletos',false,'standard',16),
  ('eventos','Dar información','dar-informacion',false,'standard',17),
  ('eventos','Apoyo logístico','apoyo-logistico',false,'standard',18),
  ('eventos','Acomodar personas','acomodar-personas',false,'standard',19),
  ('eventos','Repartir material','repartir-material',false,'standard',20),
  ('eventos','Entregar regalos','entregar-regalos',false,'standard',21),
  ('eventos','Apoyo en guardarropa','apoyo-en-guardarropa',false,'standard',22),
  ('eventos','Desmontar','desmontar',false,'standard',23),
  ('eventos','Recoger mobiliario','recoger-mobiliario',false,'standard',24),
  ('eventos','Limpiar','limpiar',false,'standard',25),
  ('eventos','Cargar equipo','cargar-equipo',false,'standard',26),
  ('eventos','Separar material','separar-material',false,'standard',27),
  ('eventos','Guardar decoración','guardar-decoracion',false,'standard',28),
  ('mesero-y-servicio-de-alimentos','Ayudante de mesero','ayudante-de-mesero',false,'standard',1),
  ('mesero-y-servicio-de-alimentos','Mesero','mesero',false,'standard',2),
  ('mesero-y-servicio-de-alimentos','Mesero de eventos','mesero-de-eventos',false,'standard',3),
  ('mesero-y-servicio-de-alimentos','Mesero de restaurante','mesero-de-restaurante',false,'standard',4),
  ('mesero-y-servicio-de-alimentos','Montar mesas','montar-mesas',false,'standard',5),
  ('mesero-y-servicio-de-alimentos','Levantar mesas','levantar-mesas',false,'standard',6),
  ('mesero-y-servicio-de-alimentos','Servir alimentos','servir-alimentos',false,'standard',7),
  ('mesero-y-servicio-de-alimentos','Servir bebidas','servir-bebidas',false,'standard',8),
  ('mesero-y-servicio-de-alimentos','Charolear','charolear',false,'standard',9),
  ('mesero-y-servicio-de-alimentos','Tomar órdenes','tomar-ordenes',false,'standard',10),
  ('mesero-y-servicio-de-alimentos','Llevar platillos','llevar-platillos',false,'standard',11),
  ('mesero-y-servicio-de-alimentos','Retirar platos','retirar-platos',false,'standard',12),
  ('mesero-y-servicio-de-alimentos','Preparar estaciones','preparar-estaciones',false,'standard',13),
  ('mesero-y-servicio-de-alimentos','Limpieza de mesas','limpieza-de-mesas',false,'standard',14),
  ('mesero-y-servicio-de-alimentos','Atención a invitados','atencion-a-invitados',false,'standard',15),
  ('mesero-y-servicio-de-alimentos','Servicio de banquetes','servicio-de-banquetes',false,'standard',16),
  ('mesero-y-servicio-de-alimentos','Servicio formal','servicio-formal',false,'standard',17),
  ('mesero-y-servicio-de-alimentos','Capitán de meseros','capitan-de-meseros',false,'standard',18),
  ('barra-y-bebidas','Ayudante de barra','ayudante-de-barra',false,'standard',1),
  ('barra-y-bebidas','Servir bebidas','servir-bebidas',false,'standard',2),
  ('barra-y-bebidas','Preparar bebidas sencillas','preparar-bebidas-sencillas',false,'standard',3),
  ('barra-y-bebidas','Preparar micheladas','preparar-micheladas',false,'standard',4),
  ('barra-y-bebidas','Preparar bebidas sin alcohol','preparar-bebidas-sin-alcohol',false,'standard',5),
  ('barra-y-bebidas','Preparar coctelería básica','preparar-cocteleria-basica',false,'standard',6),
  ('barra-y-bebidas','Preparar coctelería clásica','preparar-cocteleria-clasica',false,'standard',7),
  ('barra-y-bebidas','Manejo de cristalería','manejo-de-cristaleria',false,'standard',8),
  ('barra-y-bebidas','Montaje de barra','montaje-de-barra',false,'standard',9),
  ('barra-y-bebidas','Limpieza de barra','limpieza-de-barra',false,'standard',10),
  ('barra-y-bebidas','Control de insumos','control-de-insumos',false,'standard',11),
  ('barra-y-bebidas','Bartender básico','bartender-basico',false,'standard',12),
  ('barra-y-bebidas','Bartender de eventos','bartender-de-eventos',false,'standard',13),
  ('barra-y-bebidas','Bartender con experiencia','bartender-con-experiencia',true,'standard',14),
  ('barra-y-bebidas','Encargado de barra','encargado-de-barra',false,'standard',15),
  ('cocina','Ayudante de cocina','ayudante-de-cocina',false,'standard',1),
  ('cocina','Lavar trastes','lavar-trastes',false,'standard',2),
  ('cocina','Limpiar cocina','limpiar-cocina',false,'standard',3),
  ('cocina','Picar verdura','picar-verdura',false,'standard',4),
  ('cocina','Preparar ingredientes','preparar-ingredientes',false,'standard',5),
  ('cocina','Preparar alimentos básicos','preparar-alimentos-basicos',false,'standard',6),
  ('cocina','Preparar ensaladas','preparar-ensaladas',false,'standard',7),
  ('cocina','Preparar guarniciones','preparar-guarniciones',false,'standard',8),
  ('cocina','Preparar tortas','preparar-tortas',false,'standard',9),
  ('cocina','Preparar hamburguesas','preparar-hamburguesas',false,'standard',10),
  ('cocina','Preparar tacos','preparar-tacos',false,'standard',11),
  ('cocina','Cocina mexicana','cocina-mexicana',false,'standard',12),
  ('cocina','Parrilla','parrilla',false,'standard',13),
  ('cocina','Plancha','plancha',false,'standard',14),
  ('cocina','Freidora','freidora',false,'standard',15),
  ('cocina','Emplatado','emplatado',false,'standard',16),
  ('cocina','Empacar alimentos','empacar-alimentos',false,'standard',17),
  ('cocina','Preparación para eventos','preparacion-para-eventos',false,'standard',18),
  ('cocina','Cocinero','cocinero',false,'standard',19),
  ('cocina','Cocinero de eventos','cocinero-de-eventos',false,'standard',20),
  ('almacen-y-bodega','Acomodar mercancía','acomodar-mercancia',false,'standard',1),
  ('almacen-y-bodega','Surtir pedidos','surtir-pedidos',false,'standard',2),
  ('almacen-y-bodega','Separar pedidos','separar-pedidos',false,'standard',3),
  ('almacen-y-bodega','Empacar pedidos','empacar-pedidos',false,'standard',4),
  ('almacen-y-bodega','Etiquetar','etiquetar',false,'standard',5),
  ('almacen-y-bodega','Emplayar','emplayar',false,'standard',6),
  ('almacen-y-bodega','Flejar','flejar',false,'standard',7),
  ('almacen-y-bodega','Paletizar','paletizar',false,'standard',8),
  ('almacen-y-bodega','Contar mercancía','contar-mercancia',false,'standard',9),
  ('almacen-y-bodega','Recibir mercancía','recibir-mercancia',false,'standard',10),
  ('almacen-y-bodega','Preparar mercancía para salida','preparar-mercancia-para-salida',false,'standard',11),
  ('almacen-y-bodega','Carga','carga',false,'standard',12),
  ('almacen-y-bodega','Descarga','descarga',false,'standard',13),
  ('almacen-y-bodega','Limpieza de almacén','limpieza-de-almacen',false,'standard',14),
  ('almacen-y-bodega','Captura de entradas','captura-de-entradas',false,'standard',15),
  ('almacen-y-bodega','Captura de salidas','captura-de-salidas',false,'standard',16),
  ('almacen-y-bodega','Uso de patín hidráulico','uso-de-patin-hidraulico',false,'standard',17),
  ('almacen-y-bodega','Uso de lector de códigos','uso-de-lector-de-codigos',false,'standard',18),
  ('almacen-y-bodega','Inventario','inventario',false,'standard',19),
  ('almacen-y-bodega','Auxiliar de almacén','auxiliar-de-almacen',false,'standard',20),
  ('inventarios','Conteo físico','conteo-fisico',false,'standard',1),
  ('inventarios','Conteo de producto','conteo-de-producto',false,'standard',2),
  ('inventarios','Escaneo de códigos','escaneo-de-codigos',false,'standard',3),
  ('inventarios','Etiquetado','etiquetado',false,'standard',4),
  ('inventarios','Clasificación','clasificacion',false,'standard',5),
  ('inventarios','Captura de datos','captura-de-datos',false,'standard',6),
  ('inventarios','Comparar físico contra sistema','comparar-fisico-contra-sistema',false,'standard',7),
  ('inventarios','Conteo cíclico','conteo-ciclico',false,'standard',8),
  ('inventarios','Inventario de tienda','inventario-de-tienda',false,'standard',9),
  ('inventarios','Inventario de bodega','inventario-de-bodega',false,'standard',10),
  ('inventarios','Inventario nocturno','inventario-nocturno',false,'standard',11),
  ('inventarios','Acomodo después de inventario','acomodo-despues-de-inventario',false,'standard',12),
  ('inventarios','Uso de Excel básico','uso-de-excel-basico',false,'standard',13),
  ('inventarios','Uso de lector de códigos','uso-de-lector-de-codigos',false,'standard',14),
  ('inventarios','Auditoría física básica','auditoria-fisica-basica',false,'standard',15),
  ('tiendas-y-comercio','Acomodar producto','acomodar-producto',false,'standard',1),
  ('tiendas-y-comercio','Etiquetar precios','etiquetar-precios',false,'standard',2),
  ('tiendas-y-comercio','Surtir anaqueles','surtir-anaqueles',false,'standard',3),
  ('tiendas-y-comercio','Frenteo de producto','frenteo-de-producto',false,'standard',4),
  ('tiendas-y-comercio','Promotor','promotor',false,'standard',5),
  ('tiendas-y-comercio','Ayudante de tienda','ayudante-de-tienda',false,'standard',6),
  ('tiendas-y-comercio','Empacar compras','empacar-compras',false,'standard',7),
  ('tiendas-y-comercio','Entregar pedidos','entregar-pedidos',false,'standard',8),
  ('tiendas-y-comercio','Limpiar área','limpiar-area',false,'standard',9),
  ('tiendas-y-comercio','Recibir mercancía','recibir-mercancia',false,'standard',10),
  ('tiendas-y-comercio','Contar mercancía','contar-mercancia',false,'standard',11),
  ('tiendas-y-comercio','Apoyo en temporada alta','apoyo-en-temporada-alta',false,'standard',12),
  ('tiendas-y-comercio','Apoyo en apertura','apoyo-en-apertura',false,'standard',13),
  ('tiendas-y-comercio','Apoyo en cierre','apoyo-en-cierre',false,'standard',14),
  ('tiendas-y-comercio','Atención básica a clientes','atencion-basica-a-clientes',false,'standard',15),
  ('promotores-y-activaciones','Repartir volantes','repartir-volantes',false,'standard',1),
  ('promotores-y-activaciones','Entregar muestras','entregar-muestras',false,'standard',2),
  ('promotores-y-activaciones','Promocionar producto','promocionar-producto',false,'standard',3),
  ('promotores-y-activaciones','Invitar personas','invitar-personas',false,'standard',4),
  ('promotores-y-activaciones','Atención en stand','atencion-en-stand',false,'standard',5),
  ('promotores-y-activaciones','Demostración sencilla','demostracion-sencilla',false,'standard',6),
  ('promotores-y-activaciones','Activaciones de marca','activaciones-de-marca',false,'standard',7),
  ('promotores-y-activaciones','Botarga','botarga',false,'standard',8),
  ('promotores-y-activaciones','Edecanía','edecania',false,'standard',9),
  ('promotores-y-activaciones','Host','host',false,'standard',10),
  ('promotores-y-activaciones','Hostess','hostess',false,'standard',11),
  ('promotores-y-activaciones','Registro de asistentes','registro-de-asistentes',false,'standard',12),
  ('promotores-y-activaciones','Levantar encuestas','levantar-encuestas',false,'standard',13),
  ('promotores-y-activaciones','Recopilar datos autorizados','recopilar-datos-autorizados',false,'standard',14),
  ('promotores-y-activaciones','Colocar publicidad','colocar-publicidad',false,'standard',15),
  ('promotores-y-activaciones','Retirar publicidad','retirar-publicidad',false,'standard',16),
  ('repartos-mandados-y-diligencias','Llevar documentos','llevar-documentos',false,'standard',1),
  ('repartos-mandados-y-diligencias','Recoger documentos','recoger-documentos',false,'standard',2),
  ('repartos-mandados-y-diligencias','Entregar sobres','entregar-sobres',false,'standard',3),
  ('repartos-mandados-y-diligencias','Llevar paquetes pequeños','llevar-paquetes-pequenos',false,'standard',4),
  ('repartos-mandados-y-diligencias','Recoger paquetes','recoger-paquetes',false,'standard',5),
  ('repartos-mandados-y-diligencias','Entregar pedidos','entregar-pedidos',false,'standard',6),
  ('repartos-mandados-y-diligencias','Comprar materiales','comprar-materiales',false,'standard',7),
  ('repartos-mandados-y-diligencias','Recoger mercancía','recoger-mercancia',false,'standard',8),
  ('repartos-mandados-y-diligencias','Llevar mercancía','llevar-mercancia',false,'standard',9),
  ('repartos-mandados-y-diligencias','Hacer mandados','hacer-mandados',false,'standard',10),
  ('repartos-mandados-y-diligencias','Hacer trámites sencillos','hacer-tramites-sencillos',false,'standard',11),
  ('repartos-mandados-y-diligencias','Llevar llaves','llevar-llaves',false,'standard',12),
  ('repartos-mandados-y-diligencias','Recoger llaves','recoger-llaves',false,'standard',13),
  ('repartos-mandados-y-diligencias','Entregar invitaciones','entregar-invitaciones',false,'standard',14),
  ('repartos-mandados-y-diligencias','Entregar publicidad','entregar-publicidad',false,'standard',15),
  ('repartos-mandados-y-diligencias','Llevar un objeto de punto A a punto B','llevar-un-objeto-de-punto-a-a-punto-b',false,'standard',16),
  ('repartos-mandados-y-diligencias','Recoger un objeto y regresarlo','recoger-un-objeto-y-regresarlo',false,'standard',17),
  ('repartos-mandados-y-diligencias','Esperar y recoger un pedido','esperar-y-recoger-un-pedido',false,'standard',18),
  ('repartos-mandados-y-diligencias','Hacer fila por encargo','hacer-fila-por-encargo',false,'standard',19),
  ('repartos-mandados-y-diligencias','A pie','a-pie',false,'standard',20),
  ('repartos-mandados-y-diligencias','Bicicleta','bicicleta',false,'standard',21),
  ('repartos-mandados-y-diligencias','Motocicleta','motocicleta',false,'standard',22),
  ('repartos-mandados-y-diligencias','Automóvil','automovil',false,'standard',23),
  ('repartos-mandados-y-diligencias','Camioneta','camioneta',false,'standard',24),
  ('chofer-y-traslado','Conducir automóvil','conducir-automovil',true,'credentialed',1),
  ('chofer-y-traslado','Conducir camioneta','conducir-camioneta',true,'credentialed',2),
  ('chofer-y-traslado','Conducir vehículo estándar','conducir-vehiculo-estandar',true,'credentialed',3),
  ('chofer-y-traslado','Conducir vehículo automático','conducir-vehiculo-automatico',true,'credentialed',4),
  ('chofer-y-traslado','Trasladar mercancía','trasladar-mercancia',true,'credentialed',5),
  ('chofer-y-traslado','Recoger mercancía','recoger-mercancia',true,'credentialed',6),
  ('chofer-y-traslado','Entregar mercancía','entregar-mercancia',true,'credentialed',7),
  ('chofer-y-traslado','Apoyo en mudanza con vehículo','apoyo-en-mudanza-con-vehiculo',true,'credentialed',8),
  ('chofer-y-traslado','Chofer de reparto','chofer-de-reparto',true,'credentialed',9),
  ('chofer-y-traslado','Chofer para evento','chofer-para-evento',true,'credentialed',10),
  ('chofer-y-traslado','Traslado local','traslado-local',true,'credentialed',11),
  ('chofer-y-traslado','Licencia vigente','licencia-vigente',true,'credentialed',12),
  ('chofer-y-traslado','Tipo de licencia','tipo-de-licencia',true,'credentialed',13),
  ('chofer-y-traslado','Vehículo propio: sí/no','vehiculo-propio-si-no',true,'credentialed',14),
  ('oficina-y-captura','Captura de datos','captura-de-datos',false,'standard',1),
  ('oficina-y-captura','Digitalizar documentos','digitalizar-documentos',false,'standard',2),
  ('oficina-y-captura','Escanear','escanear',false,'standard',3),
  ('oficina-y-captura','Fotocopiar','fotocopiar',false,'standard',4),
  ('oficina-y-captura','Ordenar archivos','ordenar-archivos',false,'standard',5),
  ('oficina-y-captura','Archivar','archivar',false,'standard',6),
  ('oficina-y-captura','Clasificar documentos','clasificar-documentos',false,'standard',7),
  ('oficina-y-captura','Capturar formularios','capturar-formularios',false,'standard',8),
  ('oficina-y-captura','Excel básico','excel-basico',false,'standard',9),
  ('oficina-y-captura','Word básico','word-basico',false,'standard',10),
  ('oficina-y-captura','Hacer listas','hacer-listas',false,'standard',11),
  ('oficina-y-captura','Revisar información','revisar-informacion',false,'standard',12),
  ('oficina-y-captura','Contar documentos','contar-documentos',false,'standard',13),
  ('oficina-y-captura','Foliar documentos','foliar-documentos',false,'standard',14),
  ('oficina-y-captura','Etiquetar expedientes','etiquetar-expedientes',false,'standard',15),
  ('oficina-y-captura','Apoyo administrativo','apoyo-administrativo',false,'standard',16),
  ('oficina-y-captura','Recepción temporal','recepcion-temporal',false,'standard',17),
  ('oficina-y-captura','Contestar llamadas','contestar-llamadas',false,'standard',18),
  ('oficina-y-captura','Registrar personas','registrar-personas',false,'standard',19),
  ('tecnologia-y-computacion','Instalar computadora','instalar-computadora',true,'standard',1),
  ('tecnologia-y-computacion','Conectar computadora','conectar-computadora',true,'standard',2),
  ('tecnologia-y-computacion','Formatear computadora','formatear-computadora',true,'standard',3),
  ('tecnologia-y-computacion','Instalar programas','instalar-programas',true,'standard',4),
  ('tecnologia-y-computacion','Configurar impresora','configurar-impresora',true,'standard',5),
  ('tecnologia-y-computacion','Configurar Wi-Fi','configurar-wi-fi',true,'standard',6),
  ('tecnologia-y-computacion','Cablear red','cablear-red',true,'standard',7),
  ('tecnologia-y-computacion','Ponchar cable','ponchar-cable',true,'standard',8),
  ('tecnologia-y-computacion','Instalar cámaras','instalar-camaras',true,'standard',9),
  ('tecnologia-y-computacion','Configurar cámaras','configurar-camaras',true,'standard',10),
  ('tecnologia-y-computacion','Soporte técnico','soporte-tecnico',true,'standard',11),
  ('tecnologia-y-computacion','Mantenimiento básico de PC','mantenimiento-basico-de-pc',true,'standard',12),
  ('tecnologia-y-computacion','Limpieza de computadora','limpieza-de-computadora',true,'standard',13),
  ('tecnologia-y-computacion','Instalar Windows','instalar-windows',true,'standard',14),
  ('tecnologia-y-computacion','Respaldar archivos','respaldar-archivos',true,'standard',15),
  ('tecnologia-y-computacion','Captura de datos','captura-de-datos',true,'standard',16),
  ('tecnologia-y-computacion','Configuración básica de celular','configuracion-basica-de-celular',true,'standard',17),
  ('tecnologia-y-computacion','Configurar correo','configurar-correo',true,'standard',18),
  ('tecnologia-y-computacion','Apoyo tecnológico en eventos','apoyo-tecnologico-en-eventos',true,'standard',19),
  ('fotografia-video-y-contenido','Tomar fotografías','tomar-fotografias',false,'standard',1),
  ('fotografia-video-y-contenido','Fotografía de producto','fotografia-de-producto',false,'standard',2),
  ('fotografia-video-y-contenido','Fotografía de evento','fotografia-de-evento',false,'standard',3),
  ('fotografia-video-y-contenido','Grabar video','grabar-video',false,'standard',4),
  ('fotografia-video-y-contenido','Video para redes','video-para-redes',false,'standard',5),
  ('fotografia-video-y-contenido','Editar video básico','editar-video-basico',false,'standard',6),
  ('fotografia-video-y-contenido','Editar fotografías','editar-fotografias',false,'standard',7),
  ('fotografia-video-y-contenido','Crear reels','crear-reels',false,'standard',8),
  ('fotografia-video-y-contenido','Crear historias','crear-historias',false,'standard',9),
  ('fotografia-video-y-contenido','Apoyo en transmisión','apoyo-en-transmision',false,'standard',10),
  ('fotografia-video-y-contenido','Manejar cámara','manejar-camara',false,'standard',11),
  ('fotografia-video-y-contenido','Montar iluminación básica','montar-iluminacion-basica',false,'standard',12),
  ('fotografia-video-y-contenido','Apoyo de producción','apoyo-de-produccion',false,'standard',13),
  ('fotografia-video-y-contenido','Capturar contenido durante eventos','capturar-contenido-durante-eventos',false,'standard',14),
  ('redes-sociales-y-promocion-digital','Tomar fotos para redes','tomar-fotos-para-redes',false,'standard',1),
  ('redes-sociales-y-promocion-digital','Crear publicaciones','crear-publicaciones',false,'standard',2),
  ('redes-sociales-y-promocion-digital','Subir contenido','subir-contenido',false,'standard',3),
  ('redes-sociales-y-promocion-digital','Responder mensajes temporalmente','responder-mensajes-temporalmente',false,'standard',4),
  ('redes-sociales-y-promocion-digital','Diseñar publicaciones básicas','disenar-publicaciones-basicas',false,'standard',5),
  ('redes-sociales-y-promocion-digital','Grabar reels','grabar-reels',false,'standard',6),
  ('redes-sociales-y-promocion-digital','Editar reels','editar-reels',false,'standard',7),
  ('redes-sociales-y-promocion-digital','Publicar historias','publicar-historias',false,'standard',8),
  ('redes-sociales-y-promocion-digital','Cubrir evento en redes','cubrir-evento-en-redes',false,'standard',9),
  ('redes-sociales-y-promocion-digital','Capturar productos','capturar-productos',false,'standard',10),
  ('redes-sociales-y-promocion-digital','Crear catálogo sencillo','crear-catalogo-sencillo',false,'standard',11),
  ('belleza-y-cuidado-personal','Ayudante de salón','ayudante-de-salon',false,'standard',1),
  ('belleza-y-cuidado-personal','Lavar cabello','lavar-cabello',false,'standard',2),
  ('belleza-y-cuidado-personal','Secado','secado',false,'standard',3),
  ('belleza-y-cuidado-personal','Peinado','peinado',false,'standard',4),
  ('belleza-y-cuidado-personal','Maquillaje','maquillaje',false,'standard',5),
  ('belleza-y-cuidado-personal','Maquillaje para evento','maquillaje-para-evento',false,'standard',6),
  ('belleza-y-cuidado-personal','Uñas','unas',false,'standard',7),
  ('belleza-y-cuidado-personal','Manicure','manicure',false,'standard',8),
  ('belleza-y-cuidado-personal','Pedicure','pedicure',false,'standard',9),
  ('belleza-y-cuidado-personal','Aplicación de gel','aplicacion-de-gel',false,'standard',10),
  ('belleza-y-cuidado-personal','Aplicación de acrílico','aplicacion-de-acrilico',false,'standard',11),
  ('belleza-y-cuidado-personal','Depilación','depilacion',false,'standard',12),
  ('belleza-y-cuidado-personal','Barbería','barberia',false,'standard',13),
  ('belleza-y-cuidado-personal','Corte de cabello','corte-de-cabello',false,'standard',14),
  ('belleza-y-cuidado-personal','Apoyo en spa','apoyo-en-spa',false,'standard',15),
  ('belleza-y-cuidado-personal','Recepción de salón','recepcion-de-salon',false,'standard',16),
  ('decoracion','Decorar fiestas','decorar-fiestas',false,'standard',1),
  ('decoracion','Inflar globos','inflar-globos',false,'standard',2),
  ('decoracion','Hacer arcos de globos','hacer-arcos-de-globos',false,'standard',3),
  ('decoracion','Colocar telas','colocar-telas',false,'standard',4),
  ('decoracion','Colocar centros de mesa','colocar-centros-de-mesa',false,'standard',5),
  ('decoracion','Montar decoración','montar-decoracion',false,'standard',6),
  ('decoracion','Desmontar decoración','desmontar-decoracion',false,'standard',7),
  ('decoracion','Decorar mesas','decorar-mesas',false,'standard',8),
  ('decoracion','Decorar escenarios','decorar-escenarios',false,'standard',9),
  ('decoracion','Decoración temática','decoracion-tematica',false,'standard',10),
  ('decoracion','Envolver regalos','envolver-regalos',false,'standard',11),
  ('decoracion','Preparar recuerdos','preparar-recuerdos',false,'standard',12),
  ('decoracion','Acomodar flores','acomodar-flores',false,'standard',13),
  ('decoracion','Montar mesa de dulces','montar-mesa-de-dulces',false,'standard',14),
  ('floreria','Limpiar flores','limpiar-flores',false,'standard',1),
  ('floreria','Cortar tallos','cortar-tallos',false,'standard',2),
  ('floreria','Preparar ramos','preparar-ramos',false,'standard',3),
  ('floreria','Acomodar flores','acomodar-flores',false,'standard',4),
  ('floreria','Preparar arreglos básicos','preparar-arreglos-basicos',false,'standard',5),
  ('floreria','Transportar arreglos','transportar-arreglos',false,'standard',6),
  ('floreria','Montaje floral','montaje-floral',false,'standard',7),
  ('floreria','Desmontaje floral','desmontaje-floral',false,'standard',8),
  ('floreria','Decorar eventos','decorar-eventos',false,'standard',9),
  ('floreria','Ayudante de florería','ayudante-de-floreria',false,'standard',10),
  ('mascotas','Pasear perros','pasear-perros',true,'standard',1),
  ('mascotas','Alimentar mascotas','alimentar-mascotas',true,'standard',2),
  ('mascotas','Cuidar mascotas por unas horas','cuidar-mascotas-por-unas-horas',true,'standard',3),
  ('mascotas','Limpiar área de mascotas','limpiar-area-de-mascotas',true,'standard',4),
  ('mascotas','Bañar perros','banar-perros',true,'standard',5),
  ('mascotas','Cepillar mascotas','cepillar-mascotas',true,'standard',6),
  ('mascotas','Transportar mascotas','transportar-mascotas',true,'standard',7),
  ('mascotas','Ayudante de estética canina','ayudante-de-estetica-canina',true,'standard',8),
  ('lavado-y-limpieza-de-vehiculos','Lavar automóvil','lavar-automovil',false,'standard',1),
  ('lavado-y-limpieza-de-vehiculos','Aspirar automóvil','aspirar-automovil',false,'standard',2),
  ('lavado-y-limpieza-de-vehiculos','Limpiar interiores','limpiar-interiores',false,'standard',3),
  ('lavado-y-limpieza-de-vehiculos','Secar vehículo','secar-vehiculo',false,'standard',4),
  ('lavado-y-limpieza-de-vehiculos','Encerado básico','encerado-basico',false,'standard',5),
  ('lavado-y-limpieza-de-vehiculos','Lavado de camionetas','lavado-de-camionetas',false,'standard',6),
  ('lavado-y-limpieza-de-vehiculos','Limpieza de flotillas','limpieza-de-flotillas',false,'standard',7),
  ('lavado-y-limpieza-de-vehiculos','Ayudante de autolavado','ayudante-de-autolavado',false,'standard',8),
  ('lavado-y-limpieza-de-vehiculos','Lavado de motocicleta','lavado-de-motocicleta',false,'standard',9),
  ('mecanica-y-vehiculos','Ayudante de mecánico','ayudante-de-mecanico',true,'standard',1),
  ('mecanica-y-vehiculos','Cambio de llanta','cambio-de-llanta',true,'standard',2),
  ('mecanica-y-vehiculos','Cambio de aceite','cambio-de-aceite',true,'standard',3),
  ('mecanica-y-vehiculos','Lavado de piezas','lavado-de-piezas',true,'standard',4),
  ('mecanica-y-vehiculos','Limpieza de taller','limpieza-de-taller',true,'standard',5),
  ('mecanica-y-vehiculos','Cambio de batería','cambio-de-bateria',true,'standard',6),
  ('mecanica-y-vehiculos','Mecánica básica','mecanica-basica',true,'standard',7),
  ('mecanica-y-vehiculos','Diagnóstico básico','diagnostico-basico',true,'standard',8),
  ('mecanica-y-vehiculos','Frenos','frenos',true,'standard',9),
  ('mecanica-y-vehiculos','Suspensión','suspension',true,'standard',10),
  ('mecanica-y-vehiculos','Mecánica con experiencia','mecanica-con-experiencia',true,'standard',11),
  ('instalaciones-y-montaje','Armar muebles','armar-muebles',false,'standard',1),
  ('instalaciones-y-montaje','Instalar repisas','instalar-repisas',false,'standard',2),
  ('instalaciones-y-montaje','Colocar cuadros','colocar-cuadros',false,'standard',3),
  ('instalaciones-y-montaje','Instalar cortinas','instalar-cortinas',false,'standard',4),
  ('instalaciones-y-montaje','Instalar persianas','instalar-persianas',false,'standard',5),
  ('instalaciones-y-montaje','Montar stands','montar-stands',false,'standard',6),
  ('instalaciones-y-montaje','Montar anaqueles','montar-anaqueles',false,'standard',7),
  ('instalaciones-y-montaje','Instalar racks','instalar-racks',false,'standard',8),
  ('instalaciones-y-montaje','Armar exhibidores','armar-exhibidores',false,'standard',9),
  ('instalaciones-y-montaje','Instalar señalización','instalar-senalizacion',false,'standard',10),
  ('instalaciones-y-montaje','Colocar lonas','colocar-lonas',false,'standard',11),
  ('instalaciones-y-montaje','Montar pantallas','montar-pantallas',false,'standard',12),
  ('instalaciones-y-montaje','Colocar proyectores','colocar-proyectores',false,'standard',13),
  ('instalaciones-y-montaje','Apoyo en instalación','apoyo-en-instalacion',false,'standard',14),
  ('audio-iluminacion-y-eventos-tecnicos','Cargar bocinas','cargar-bocinas',false,'standard',1),
  ('audio-iluminacion-y-eventos-tecnicos','Montar bocinas','montar-bocinas',false,'standard',2),
  ('audio-iluminacion-y-eventos-tecnicos','Desmontar audio','desmontar-audio',false,'standard',3),
  ('audio-iluminacion-y-eventos-tecnicos','Tender cable','tender-cable',false,'standard',4),
  ('audio-iluminacion-y-eventos-tecnicos','Montar iluminación','montar-iluminacion',false,'standard',5),
  ('audio-iluminacion-y-eventos-tecnicos','Desmontar iluminación','desmontar-iluminacion',false,'standard',6),
  ('audio-iluminacion-y-eventos-tecnicos','Instalar micrófonos','instalar-microfonos',false,'standard',7),
  ('audio-iluminacion-y-eventos-tecnicos','Apoyo de DJ','apoyo-de-dj',false,'standard',8),
  ('audio-iluminacion-y-eventos-tecnicos','Operador de audio','operador-de-audio',false,'standard',9),
  ('audio-iluminacion-y-eventos-tecnicos','Operador de iluminación','operador-de-iluminacion',false,'standard',10),
  ('audio-iluminacion-y-eventos-tecnicos','Apoyo técnico en eventos','apoyo-tecnico-en-eventos',false,'standard',11),
  ('costura-y-textiles','Costura básica','costura-basica',false,'standard',1),
  ('costura-y-textiles','Dobladillos','dobladillos',false,'standard',2),
  ('costura-y-textiles','Arreglos sencillos','arreglos-sencillos',false,'standard',3),
  ('costura-y-textiles','Botones','botones',false,'standard',4),
  ('costura-y-textiles','Empaque de ropa','empaque-de-ropa',false,'standard',5),
  ('costura-y-textiles','Etiquetado de ropa','etiquetado-de-ropa',false,'standard',6),
  ('costura-y-textiles','Planchado','planchado',false,'standard',7),
  ('costura-y-textiles','Doblar prendas','doblar-prendas',false,'standard',8),
  ('costura-y-textiles','Clasificar prendas','clasificar-prendas',false,'standard',9),
  ('costura-y-textiles','Ayudante de taller','ayudante-de-taller',false,'standard',10),
  ('costura-y-textiles','Máquina de coser','maquina-de-coser',false,'standard',11),
  ('costura-y-textiles','Costura con experiencia','costura-con-experiencia',true,'standard',12),
  ('empaque-y-produccion','Empacar producto','empacar-producto',false,'standard',1),
  ('empaque-y-produccion','Embolsar','embolsar',false,'standard',2),
  ('empaque-y-produccion','Sellar bolsas','sellar-bolsas',false,'standard',3),
  ('empaque-y-produccion','Etiquetar','etiquetar',false,'standard',4),
  ('empaque-y-produccion','Armar cajas','armar-cajas',false,'trusted',5),
  ('empaque-y-produccion','Doblar cajas','doblar-cajas',false,'trusted',6),
  ('empaque-y-produccion','Ensamblar piezas sencillas','ensamblar-piezas-sencillas',false,'standard',7),
  ('empaque-y-produccion','Contar piezas','contar-piezas',false,'standard',8),
  ('empaque-y-produccion','Separar piezas','separar-piezas',false,'standard',9),
  ('empaque-y-produccion','Revisar producto','revisar-producto',false,'standard',10),
  ('empaque-y-produccion','Clasificar producto','clasificar-producto',false,'standard',11),
  ('empaque-y-produccion','Emplayar','emplayar',false,'standard',12),
  ('empaque-y-produccion','Preparar pedidos','preparar-pedidos',false,'standard',13),
  ('empaque-y-produccion','Trabajo en línea','trabajo-en-linea',false,'standard',14),
  ('empaque-y-produccion','Apoyo de producción','apoyo-de-produccion',false,'standard',15),
  ('ferias-mercados-y-tianguis','Montar puesto','montar-puesto',false,'standard',1),
  ('ferias-mercados-y-tianguis','Desmontar puesto','desmontar-puesto',false,'standard',2),
  ('ferias-mercados-y-tianguis','Cargar mercancía','cargar-mercancia',false,'standard',3),
  ('ferias-mercados-y-tianguis','Descargar mercancía','descargar-mercancia',false,'standard',4),
  ('ferias-mercados-y-tianguis','Acomodar producto','acomodar-producto',false,'standard',5),
  ('ferias-mercados-y-tianguis','Atender puesto','atender-puesto',false,'standard',6),
  ('ferias-mercados-y-tianguis','Cobro básico','cobro-basico',false,'trusted',7),
  ('ferias-mercados-y-tianguis','Empacar compras','empacar-compras',false,'standard',8),
  ('ferias-mercados-y-tianguis','Repartir muestras','repartir-muestras',false,'standard',9),
  ('ferias-mercados-y-tianguis','Limpiar puesto','limpiar-puesto',false,'standard',10),
  ('ferias-mercados-y-tianguis','Vigilar mercancía durante operación','vigilar-mercancia-durante-operacion',false,'standard',11),
  ('ferias-mercados-y-tianguis','Apoyo general','apoyo-general',false,'standard',12),
  ('restaurantes-y-comida-rapida','Ayudante general','ayudante-general',false,'standard',1),
  ('restaurantes-y-comida-rapida','Lavaloza','lavaloza',false,'standard',2),
  ('restaurantes-y-comida-rapida','Limpieza','limpieza',false,'standard',3),
  ('restaurantes-y-comida-rapida','Mesero','mesero',false,'standard',4),
  ('restaurantes-y-comida-rapida','Runner','runner',false,'standard',5),
  ('restaurantes-y-comida-rapida','Garrotero','garrotero',false,'standard',6),
  ('restaurantes-y-comida-rapida','Ayudante de cocina','ayudante-de-cocina',false,'standard',7),
  ('restaurantes-y-comida-rapida','Parrilla','parrilla',false,'standard',8),
  ('restaurantes-y-comida-rapida','Freidora','freidora',false,'standard',9),
  ('restaurantes-y-comida-rapida','Plancha','plancha',false,'standard',10),
  ('restaurantes-y-comida-rapida','Empaque','empaque',false,'standard',11),
  ('restaurantes-y-comida-rapida','Preparación de pedidos','preparacion-de-pedidos',false,'standard',12),
  ('restaurantes-y-comida-rapida','Entrega en mostrador','entrega-en-mostrador',false,'standard',13),
  ('restaurantes-y-comida-rapida','Montaje','montaje',false,'standard',14),
  ('restaurantes-y-comida-rapida','Cierre de restaurante','cierre-de-restaurante',false,'standard',15),
  ('hoteles-y-hospedaje','Limpieza de habitaciones','limpieza-de-habitaciones',false,'standard',1),
  ('hoteles-y-hospedaje','Tender camas','tender-camas',false,'standard',2),
  ('hoteles-y-hospedaje','Limpieza de áreas comunes','limpieza-de-areas-comunes',false,'standard',3),
  ('hoteles-y-hospedaje','Lavandería','lavanderia',false,'standard',4),
  ('hoteles-y-hospedaje','Ayudante de cocina','ayudante-de-cocina',false,'standard',5),
  ('hoteles-y-hospedaje','Mesero','mesero',false,'standard',6),
  ('hoteles-y-hospedaje','Bellboy temporal','bellboy-temporal',false,'standard',7),
  ('hoteles-y-hospedaje','Montaje de salón','montaje-de-salon',false,'standard',8),
  ('hoteles-y-hospedaje','Desmontaje de salón','desmontaje-de-salon',false,'standard',9),
  ('hoteles-y-hospedaje','Apoyo en eventos','apoyo-en-eventos',false,'standard',10),
  ('hoteles-y-hospedaje','Recepción temporal','recepcion-temporal',false,'standard',11),
  ('hoteles-y-hospedaje','Carga de equipaje','carga-de-equipaje',false,'standard',12),
  ('lavanderia','Separar ropa','separar-ropa',false,'standard',1),
  ('lavanderia','Lavar','lavar',false,'standard',2),
  ('lavanderia','Secar','secar',false,'standard',3),
  ('lavanderia','Doblar','doblar',false,'standard',4),
  ('lavanderia','Planchar','planchar',false,'standard',5),
  ('lavanderia','Empacar','empacar',false,'standard',6),
  ('lavanderia','Etiquetar prendas','etiquetar-prendas',false,'standard',7),
  ('lavanderia','Recepción de ropa','recepcion-de-ropa',false,'standard',8),
  ('lavanderia','Entrega de ropa','entrega-de-ropa',false,'standard',9),
  ('lavanderia','Limpieza del área','limpieza-del-area',false,'standard',10),
  ('escuelas-cursos-y-talleres','Registrar asistentes','registrar-asistentes',false,'standard',1),
  ('escuelas-cursos-y-talleres','Acomodar sillas','acomodar-sillas',false,'standard',2),
  ('escuelas-cursos-y-talleres','Entregar material','entregar-material',false,'standard',3),
  ('escuelas-cursos-y-talleres','Preparar salón','preparar-salon',false,'standard',4),
  ('escuelas-cursos-y-talleres','Limpiar salón','limpiar-salon',false,'standard',5),
  ('escuelas-cursos-y-talleres','Apoyo al instructor','apoyo-al-instructor',false,'standard',6),
  ('escuelas-cursos-y-talleres','Control de acceso','control-de-acceso',false,'standard',7),
  ('escuelas-cursos-y-talleres','Capturar asistencia','capturar-asistencia',false,'standard',8),
  ('escuelas-cursos-y-talleres','Entregar constancias','entregar-constancias',false,'standard',9),
  ('escuelas-cursos-y-talleres','Montaje y desmontaje','montaje-y-desmontaje',false,'standard',10),
  ('logistica','Recibir mercancía','recibir-mercancia',false,'standard',1),
  ('logistica','Registrar mercancía','registrar-mercancia',false,'standard',2),
  ('logistica','Clasificar','clasificar',false,'standard',3),
  ('logistica','Preparar pedidos','preparar-pedidos',false,'standard',4),
  ('logistica','Empacar','empacar',false,'standard',5),
  ('logistica','Etiquetar','etiquetar',false,'standard',6),
  ('logistica','Organizar rutas','organizar-rutas',false,'standard',7),
  ('logistica','Entregar material','entregar-material',false,'standard',8),
  ('logistica','Conteos','conteos',false,'standard',9),
  ('logistica','Apoyo en embarques','apoyo-en-embarques',false,'standard',10),
  ('logistica','Apoyo en recepción','apoyo-en-recepcion',false,'standard',11),
  ('logistica','Carga y descarga','carga-y-descarga',false,'standard',12),
  ('logistica','Control sencillo de entradas y salidas','control-sencillo-de-entradas-y-salidas',false,'standard',13),
  ('volanteo-y-publicidad-fisica','Repartir volantes','repartir-volantes',false,'standard',1),
  ('volanteo-y-publicidad-fisica','Colocar carteles autorizados','colocar-carteles-autorizados',false,'standard',2),
  ('volanteo-y-publicidad-fisica','Entregar tarjetas','entregar-tarjetas',false,'standard',3),
  ('volanteo-y-publicidad-fisica','Entregar promociones','entregar-promociones',false,'standard',4),
  ('volanteo-y-publicidad-fisica','Repartir cupones','repartir-cupones',false,'standard',5),
  ('volanteo-y-publicidad-fisica','Activación en crucero','activacion-en-crucero',false,'standard',6),
  ('volanteo-y-publicidad-fisica','Activación en plaza','activacion-en-plaza',false,'standard',7),
  ('volanteo-y-publicidad-fisica','Activación en evento','activacion-en-evento',false,'standard',8),
  ('volanteo-y-publicidad-fisica','Entrega casa por casa donde sea legal','entrega-casa-por-casa-donde-sea-legal',false,'standard',9),
  ('volanteo-y-publicidad-fisica','Retiro de publicidad','retiro-de-publicidad',false,'standard',10),
  ('atencion-al-cliente-temporal','Recibir personas','recibir-personas',false,'standard',1),
  ('atencion-al-cliente-temporal','Dar indicaciones','dar-indicaciones',false,'standard',2),
  ('atencion-al-cliente-temporal','Resolver dudas básicas','resolver-dudas-basicas',false,'standard',3),
  ('atencion-al-cliente-temporal','Registrar visitantes','registrar-visitantes',false,'standard',4),
  ('atencion-al-cliente-temporal','Entregar turnos','entregar-turnos',false,'standard',5),
  ('atencion-al-cliente-temporal','Entregar material','entregar-material',false,'standard',6),
  ('atencion-al-cliente-temporal','Orientar asistentes','orientar-asistentes',false,'standard',7),
  ('atencion-al-cliente-temporal','Atención en módulo','atencion-en-modulo',false,'standard',8),
  ('atencion-al-cliente-temporal','Atención en stand','atencion-en-stand',false,'standard',9),
  ('atencion-al-cliente-temporal','Recepción temporal','recepcion-temporal',false,'standard',10),
  ('atencion-al-cliente-temporal','Confirmar nombres en lista','confirmar-nombres-en-lista',false,'standard',11),
  ('cobro-y-caja','Cobro en efectivo','cobro-en-efectivo',true,'trusted',1),
  ('cobro-y-caja','Terminal bancaria','terminal-bancaria',true,'trusted',2),
  ('cobro-y-caja','Caja registradora','caja-registradora',true,'trusted',3),
  ('cobro-y-caja','Cobro en evento','cobro-en-evento',true,'trusted',4),
  ('cobro-y-caja','Cobro en puesto','cobro-en-puesto',true,'trusted',5),
  ('cobro-y-caja','Corte básico','corte-basico',true,'trusted',6),
  ('cobro-y-caja','Entrega de cambio','entrega-de-cambio',true,'trusted',7),
  ('cobro-y-caja','Registro de ventas','registro-de-ventas',true,'trusted',8),
  ('cobro-y-caja','Punto de venta','punto-de-venta',true,'trusted',9),
  ('seguridad-y-control-de-acceso','Control de lista','control-de-lista',true,'credentialed',1),
  ('seguridad-y-control-de-acceso','Revisar pulseras','revisar-pulseras',true,'credentialed',2),
  ('seguridad-y-control-de-acceso','Revisar boletos','revisar-boletos',true,'credentialed',3),
  ('seguridad-y-control-de-acceso','Orientar acceso','orientar-acceso',true,'credentialed',4),
  ('seguridad-y-control-de-acceso','Controlar filas','controlar-filas',true,'credentialed',5),
  ('seguridad-y-control-de-acceso','Apoyo de acceso en eventos','apoyo-de-acceso-en-eventos',true,'credentialed',6),
  ('seguridad-y-control-de-acceso','Vigilar área sin funciones de seguridad privada','vigilar-area-sin-funciones-de-seguridad-privada',true,'credentialed',7),
  ('limpieza-de-terrenos-y-exteriores','Barrer calle o patio','barrer-calle-o-patio',false,'standard',1),
  ('limpieza-de-terrenos-y-exteriores','Recoger basura','recoger-basura',false,'standard',2),
  ('limpieza-de-terrenos-y-exteriores','Retirar hojas','retirar-hojas',false,'standard',3),
  ('limpieza-de-terrenos-y-exteriores','Deshierbar','deshierbar',false,'standard',4),
  ('limpieza-de-terrenos-y-exteriores','Mover ramas','mover-ramas',false,'standard',5),
  ('limpieza-de-terrenos-y-exteriores','Limpiar terreno','limpiar-terreno',false,'standard',6),
  ('limpieza-de-terrenos-y-exteriores','Retirar objetos','retirar-objetos',false,'standard',7),
  ('limpieza-de-terrenos-y-exteriores','Cargar residuos','cargar-residuos',false,'standard',8),
  ('limpieza-de-terrenos-y-exteriores','Apilar material','apilar-material',false,'standard',9),
  ('limpieza-de-terrenos-y-exteriores','Limpieza después de evento exterior','limpieza-despues-de-evento-exterior',false,'standard',10),
  ('recoleccion-y-separacion','Separar cartón','separar-carton',false,'standard',1),
  ('recoleccion-y-separacion','Separar plástico','separar-plastico',false,'standard',2),
  ('recoleccion-y-separacion','Separar material','separar-material',false,'standard',3),
  ('recoleccion-y-separacion','Compactar cajas','compactar-cajas',false,'trusted',4),
  ('recoleccion-y-separacion','Desarmar cajas','desarmar-cajas',false,'trusted',5),
  ('recoleccion-y-separacion','Clasificar reciclables','clasificar-reciclables',false,'standard',6),
  ('recoleccion-y-separacion','Cargar reciclables','cargar-reciclables',false,'standard',7),
  ('recoleccion-y-separacion','Limpieza de área','limpieza-de-area',false,'standard',8),
  ('recoleccion-y-separacion','Apoyo en centros de acopio','apoyo-en-centros-de-acopio',false,'standard',9),
  ('armado-de-pedidos-y-comercio-electronico','Recibir pedido','recibir-pedido',false,'standard',1),
  ('armado-de-pedidos-y-comercio-electronico','Buscar producto','buscar-producto',false,'standard',2),
  ('armado-de-pedidos-y-comercio-electronico','Preparar pedido','preparar-pedido',false,'standard',3),
  ('armado-de-pedidos-y-comercio-electronico','Empacar','empacar',false,'standard',4),
  ('armado-de-pedidos-y-comercio-electronico','Etiquetar','etiquetar',false,'standard',5),
  ('armado-de-pedidos-y-comercio-electronico','Sellar','sellar',false,'standard',6),
  ('armado-de-pedidos-y-comercio-electronico','Imprimir guía','imprimir-guia',false,'standard',7),
  ('armado-de-pedidos-y-comercio-electronico','Clasificar pedidos','clasificar-pedidos',false,'standard',8),
  ('armado-de-pedidos-y-comercio-electronico','Organizar paquetes','organizar-paquetes',false,'standard',9),
  ('armado-de-pedidos-y-comercio-electronico','Entregar a paquetería','entregar-a-paqueteria',false,'standard',10),
  ('armado-de-pedidos-y-comercio-electronico','Inventario básico','inventario-basico',false,'standard',11),
  ('armado-de-pedidos-y-comercio-electronico','Devoluciones sencillas','devoluciones-sencillas',false,'standard',12),
  ('trabajos-sencillos-por-encargo','Llevar algo','llevar-algo',false,'standard',1),
  ('trabajos-sencillos-por-encargo','Recoger algo','recoger-algo',false,'standard',2),
  ('trabajos-sencillos-por-encargo','Acomodar algo','acomodar-algo',false,'standard',3),
  ('trabajos-sencillos-por-encargo','Limpiar algo','limpiar-algo',false,'standard',4),
  ('trabajos-sencillos-por-encargo','Armar algo','armar-algo',false,'standard',5),
  ('trabajos-sencillos-por-encargo','Desarmar algo','desarmar-algo',false,'standard',6),
  ('trabajos-sencillos-por-encargo','Esperar una entrega','esperar-una-entrega',false,'standard',7),
  ('trabajos-sencillos-por-encargo','Recibir un paquete','recibir-un-paquete',false,'standard',8),
  ('trabajos-sencillos-por-encargo','Hacer una compra','hacer-una-compra',false,'standard',9),
  ('trabajos-sencillos-por-encargo','Entregar un documento','entregar-un-documento',false,'standard',10),
  ('trabajos-sencillos-por-encargo','Recoger documentos','recoger-documentos',false,'standard',11),
  ('trabajos-sencillos-por-encargo','Hacer fila','hacer-fila',false,'standard',12),
  ('trabajos-sencillos-por-encargo','Ayudar unas horas','ayudar-unas-horas',false,'standard',13),
  ('trabajos-sencillos-por-encargo','Contar objetos','contar-objetos',false,'standard',14),
  ('trabajos-sencillos-por-encargo','Separar objetos','separar-objetos',false,'standard',15),
  ('trabajos-sencillos-por-encargo','Empacar cosas','empacar-cosas',false,'standard',16),
  ('trabajos-sencillos-por-encargo','Mover objetos','mover-objetos',false,'standard',17),
  ('trabajos-sencillos-por-encargo','Preparar un espacio','preparar-un-espacio',false,'standard',18),
  ('trabajos-sencillos-por-encargo','Recoger después de un evento','recoger-despues-de-un-evento',false,'standard',19),
  ('trabajos-sencillos-por-encargo','Apoyo general por unas horas','apoyo-general-por-unas-horas',false,'standard',20)
)
insert into public.work_skills(category_id,name,slug,requires_verification,trust_level,active,sort_order)
select c.id,x.name,x.slug,x.requires_verification,x.trust_level,true,x.sort_order
from catalog x join public.work_categories c on c.slug=x.category_slug
on conflict(category_id,slug) do update set name=excluded.name,requires_verification=excluded.requires_verification,trust_level=excluded.trust_level,active=true,sort_order=excluded.sort_order;

-- Relaciona datos existentes con el nuevo catálogo sin cambiar sus textos visibles.
update public.jobs j set work_category_id=c.id from public.work_categories c where lower(c.name)=lower(j.category) or (j.category='Mesero' and c.slug='mesero-y-servicio-de-alimentos') or (j.category='Almacén' and c.slug='almacen-y-bodega') or (j.category='Campo' and c.slug='campo-y-actividades-agricolas');

-- Índice rápido de las categorías que ya eligieron los trabajadores.
insert into public.worker_categories(worker_id,category_id)
select distinct w.profile_id,c.id from public.workers w cross join lateral unnest(w.categories) as u(old_name) join public.work_categories c on lower(c.name)=lower(u.old_name) or (u.old_name='Mesero' and c.slug='mesero-y-servicio-de-alimentos') or (u.old_name='Almacén' and c.slug='almacen-y-bodega') or (u.old_name='Campo' and c.slug='campo-y-actividades-agricolas')
on conflict do nothing;
