import Link from "next/link"; 
import { notFound } from "next/navigation"; 
import { cancelJobAction,employerFinishAction,reportPaymentAction,selectApplicationAction } from "@/app/actions"; 
import { Notice } from "@/components/notice"; 
import { StatusPill } from "@/components/status-pill"; 
import { SubmitButton } from "@/components/submit-button"; 
import { requireUser } from "@/lib/auth"; 
import { createClient } from "@/lib/supabase/server"; 
import { formatDate,money } from "@/lib/config"; 
 
type CandidateSkill={name:string;level:"helper"|"capable"|"experienced";verified:boolean}; 
type Candidate={application_id:string;worker_id:string;full_name:string;categories:string[];completed_jobs:number;rating:number|null;attendance:number|null;is_new:boolean;status:string;phone:string|null;skills?:CandidateSkill[]}; 
type Package={posts:number;price:number;label:string}; 
export default async function EmployerJob({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){ 
  const {id}=await params; const q=await searchParams; await requireUser("employer"); const supabase=await createClient(); 

  const [jobResult,candidateResult,paymentResult,packageResult,skillResult]=await Promise.all([ 
    supabase.from("jobs").select("id,title,category,workers_needed,zone,job_date,start_time,duration_hours,pay_amount,status").eq("id",id).maybeSingle(),
    supabase.rpc("get_job_candidates",{p_job_id:id}),
    supabase.from("payments").select("status,package_label,amount,reference").eq("job_id",id).maybeSingle(),
    supabase.from("app_settings").select("value").eq("key","publication_packages").maybeSingle(),
    supabase.rpc("get_job_candidate_skills",{p_job_id:id}), 
  ]); 

  const job=jobResult.data;
  const candidates=candidateResult.data;
  const payment=paymentResult.data;
  const packageSetting=packageResult.data;
  const candidateSkills=skillResult.data;

  if(!job)notFound(); 
  const ended=new Date(`${job.job_date}T${job.start_time}`).getTime()+Number(job.duration_hours)*3600000<Date.now(); const skillRows=(candidateSkills??[]) as Array<{worker_id:string;skills:CandidateSkill[]}>; const skillMap=new Map<string,CandidateSkill[]>(skillRows.map(row=>[row.worker_id,row.skills??[]])); const list:Candidate[]=((candidates??[]) as Candidate[]).map(candidate=>({...candidate,skills:skillMap.get(candidate.worker_id)??[]})); const packages=(packageSetting?.value??[{posts:6,price:200,label:"Paquete Arranque"},{posts:9,price:350,label:"Paquete Movimiento"}]) as Package[]; 
  return <main className="shell py-7 max-w-4xl"><Link href="/employer" className="text-sm font-bold muted">← Mis jales</Link><article className="card p-6 mt-4"> 
    <div className="flex items-start justify-between gap-3"><div><span className="pill">{job.category}</span><h1 className="text-3xl font-black mt-3">{job.title}</h1><p className="muted mt-1">{formatDate(job.job_date)} · {job.start_time.slice(0,5)} · {job.zone}</p></div><StatusPill status={job.status}/></div> 
    {q.error&&<div className="mt-4"><Notice type="error">{q.error}</Notice></div>}{q.message&&<div className="mt-4"><Notice type="success">{q.message}</Notice></div>} 
    <div className="grid grid-cols-3 gap-3 mt-6 text-center"><div className="rounded-xl bg-[#eef5ed] p-3"><strong className="text-xl">{job.workers_needed}</strong><p className="text-xs muted">Necesarios</p></div><div className="rounded-xl bg-[#eef5ed] p-3"><strong className="text-xl">{list.length}</strong><p className="text-xs muted">Interesados</p></div><div className="rounded-xl bg-[#eef5ed] p-3"><strong className="text-xl">{money(job.pay_amount)}</strong><p className="text-xs muted">Por persona</p></div></div> 
    {job.status==="awaiting_payment"&&<section className="payment-packages"><span>ELIGE CÓMO PUBLICAR</span><h2>Una publicación o un paquete</h2><p>Primero transfiere el paquete que prefieras usando la referencia de abajo. Después toca el botón del paquete para avisarnos; las publicaciones restantes se cargarán como créditos cuando administración confirme el pago.</p>{payment?.status==="reported"?<div className="reported-payment"><Notice type="info">Pago pendiente por verificar. Te avisaremos al publicarlo.</Notice><p><b>{payment.package_label??"Paquete seleccionado"}</b> · {money(payment.amount)}</p><p>Concepto de transferencia: <strong>{payment.reference}</strong></p></div>:<div className="package-grid">{packages.map(pack=><form action={reportPaymentAction} key={pack.posts} className="package-option"><input type="hidden" name="job_id" value={id}/><input type="hidden" name="package_posts" value={pack.posts}/><small>{pack.label}</small><strong>{pack.posts} {pack.posts===1?"publicación":"publicaciones"}</strong><b>{money(pack.price)}</b>{pack.posts>1&&<em>{money(pack.price/pack.posts)} cada una</em>}<button>YA TRANSFERÍ ESTE PAQUETE</button></form>)}</div>}<div className="bank-transfer"><span>DATOS PARA TRANSFERIR</span><p>Banco: <b>{process.env.NEXT_PUBLIC_BANK_NAME??"Nu México"}</b></p><p>Cuenta/CLABE: <b>{process.env.NEXT_PUBLIC_BANK_ACCOUNT??"Configura la cuenta en Railway"}</b></p><p>Beneficiario: <b>{process.env.NEXT_PUBLIC_BANK_BENEFICIARY??"Titular por configurar"}</b></p><p>Usa como concepto la referencia <b>{payment?.reference??`JALE-${id.replaceAll("-","").slice(0,8).toUpperCase()}`}</b>. Es obligatoria para ubicar tu pago.</p></div></section>} 
  </article> 
  <section className="mt-7"><h2 className="section-title">Personas interesadas</h2><p className="text-sm muted mt-1">Lista mezclada para repartir oportunidades. El teléfono aparece sólo al seleccionar.</p><div className="grid gap-4 mt-4">{list.map(c=><article className="card p-5" key={c.application_id}><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="text-xl font-black">{c.full_name}</h3>{c.is_new&&<span className="pill">Nuevo</span>}</div><p className="text-sm muted mt-1">{c.categories.join(" · ")}</p>{Boolean(c.skills?.length)&&<div className="mt-2 flex flex-wrap gap-1">{c.skills?.slice(0,8).map(skill=><span className="pill" key={skill.name}>{skill.name} · {skill.level==="experienced"?"Con experiencia":skill.level==="capable"?"Sabe hacerlo":"Puede ayudar"}{skill.verified?" ✓":""}</span>)}</div>}</div><StatusPill status={c.status}/></div><div className="grid grid-cols-3 gap-2 mt-4 text-sm"><p><b>{c.completed_jobs}</b><br/><span className="muted">Jales</span></p><p><b>{c.rating??"—"}</b><br/><span className="muted">Rating</span></p><p><b>{c.attendance?`${c.attendance}%`:"—"}</b><br/><span className="muted">Asistencia</span></p></div>{c.phone&&<p className="mt-4 rounded-xl bg-[#eef5ed] p-3 font-bold">Teléfono: <a className="underline" href={`tel:${c.phone}`}>{c.phone}</a></p>}{c.status==="interested"&&<form action={selectApplicationAction} className="mt-4"><input type="hidden" name="job_id" value={id}/><input type="hidden" name="application_id" value={c.application_id}/><SubmitButton>SELECCIONAR</SubmitButton></form>}{c.status==="confirmed"&&ended&&<details className="mt-4 rounded-xl border border-[#dfe4dc] p-4"><summary className="font-black cursor-pointer">MARCAR JALE TERMINADO</summary><form action={employerFinishAction} className="grid gap-3 mt-4"><input type="hidden" name="job_id" value={id}/><input type="hidden" name="application_id" value={c.application_id}/><label className="label">¿Se presentó?<select className="field" name="presented"><option value="true">Sí</option><option value="false">No</option></select></label><label className="label">Calificación<select className="field" name="rating">{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></label><textarea className="field" name="comment" maxLength={300} placeholder="Comentario opcional"/><SubmitButton>GUARDAR FINALIZACIÓN</SubmitButton></form></details>}</article>)}{!list.length&&<div className="card p-7 text-center muted">Aún no hay personas interesadas.</div>}</div> 
    {["draft","awaiting_payment","open","candidates_available"].includes(job.status)&&<details className="mt-8 rounded-xl bg-red-50 p-4"><summary className="font-bold cursor-pointer text-red-900">Cancelar este jale</summary><p className="text-sm mt-3">Se cerrarán las postulaciones pendientes. Esta acción no recupera una publicación gratis.</p><form action={cancelJobAction} className="mt-3"><input type="hidden" name="job_id" value={id}/><button className="btn bg-red-700 text-white w-full">CONFIRMAR CANCELACIÓN</button></form></details>} 
  </section></main>; 
} 
